"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Attachment, ConfirmCustomizationDetailsRequest,
                     CreateAmazonMotorsRequest, CreateAmazonMotorsRequestBody,
                     CreateAmazonMotorsResponse,
                     CreateConfirmCustomizationDetailsRequestBody,
                     CreateConfirmCustomizationDetailsResponse,
                     CreateConfirmDeliveryDetailsRequest,
                     CreateConfirmDeliveryDetailsRequestBody,
                     CreateConfirmDeliveryDetailsResponse,
                     CreateConfirmOrderDetailsRequest,
                     CreateConfirmOrderDetailsRequestBody,
                     CreateConfirmOrderDetailsResponse,
                     CreateConfirmServiceDetailsRequest,
                     CreateConfirmServiceDetailsRequestBody,
                     CreateConfirmServiceDetailsResponse,
                     CreateDigitalAccessKeyRequest,
                     CreateDigitalAccessKeyRequestBody,
                     CreateDigitalAccessKeyResponse,
                     CreateLegalDisclosureRequest,
                     CreateLegalDisclosureRequestBody,
                     CreateLegalDisclosureResponse,
                     CreateNegativeFeedbackRemovalRequest,
                     CreateNegativeFeedbackRemovalResponse,
                     CreateUnexpectedProblemRequest,
                     CreateUnexpectedProblemRequestBody,
                     CreateUnexpectedProblemResponse, CreateWarrantyRequest,
                     CreateWarrantyRequestBody, CreateWarrantyResponse, Error,
                     ErrorList, GetAttributesRequest, GetAttributesResponse,
                     GetMessagingActionResponse,
                     GetMessagingActionsForOrderRequest,
                     GetMessagingActionsForOrderResponse, GetSchemaResponse,
                     InvoiceRequestBody, InvoiceResponse, LinkObject,
                     MessagingAction, Schema, SendInvoiceRequest)

__all__ = [
    "Attachment",
    "LinkObject",
    "MessagingAction",
    "Schema",
    "GetMessagingActionsForOrderResponse",
    "GetMessagingActionResponse",
    "GetSchemaResponse",
    "InvoiceRequestBody",
    "InvoiceResponse",
    "CreateConfirmCustomizationDetailsRequestBody",
    "CreateConfirmCustomizationDetailsResponse",
    "CreateConfirmDeliveryDetailsRequestBody",
    "CreateConfirmDeliveryDetailsResponse",
    "CreateNegativeFeedbackRemovalResponse",
    "CreateLegalDisclosureRequestBody",
    "CreateLegalDisclosureResponse",
    "CreateConfirmOrderDetailsRequestBody",
    "CreateConfirmOrderDetailsResponse",
    "CreateConfirmServiceDetailsRequestBody",
    "CreateConfirmServiceDetailsResponse",
    "CreateAmazonMotorsRequestBody",
    "CreateAmazonMotorsResponse",
    "CreateWarrantyRequestBody",
    "CreateWarrantyResponse",
    "GetAttributesResponse",
    "CreateDigitalAccessKeyRequestBody",
    "CreateDigitalAccessKeyResponse",
    "CreateUnexpectedProblemRequestBody",
    "CreateUnexpectedProblemResponse",
    "ErrorList",
    "Error",
    "GetMessagingActionsForOrderRequest",
    "ConfirmCustomizationDetailsRequest",
    "CreateConfirmDeliveryDetailsRequest",
    "CreateLegalDisclosureRequest",
    "CreateNegativeFeedbackRemovalRequest",
    "CreateConfirmOrderDetailsRequest",
    "CreateConfirmServiceDetailsRequest",
    "CreateAmazonMotorsRequest",
    "CreateWarrantyRequest",
    "GetAttributesRequest",
    "CreateDigitalAccessKeyRequest",
    "CreateUnexpectedProblemRequest",
    "SendInvoiceRequest",
]
