"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, CancelInboundRequest, CarrierCode,
                     CarrierCodeType, CheckInboundEligibilityRequest,
                     ConfirmInboundRequest, CreateInboundRequest,
                     DestinationDetails, DimensionUnitOfMeasurement,
                     DistributionPackage, DistributionPackageContents,
                     DistributionPackageQuantity, DistributionPackageType,
                     Error, ErrorList, ExpirationDetails, GetInboundRequest,
                     GetInboundShipmentLabelsRequest,
                     GetInboundShipmentRequest, InboundEligibility,
                     InboundEligibilityStatus, InboundOrder,
                     InboundOrderCreationData, InboundOrderReference,
                     InboundPackages, InboundPreferences, InboundShipment,
                     InboundShipmentStatus, InboundShipmentSummary,
                     InboundStatus, InventoryDetails, InventoryListing,
                     InventoryQuantity, InventorySummary,
                     InventoryUnitOfMeasurement, LabelOwner, LabelStatus,
                     ListInboundShipmentsRequest, ListInventoryRequest,
                     MeasurementData, OrderIneligibilityReason,
                     PackageDimensions, PackageVolume, PackageWeight,
                     PrepCategory, PrepDetails, PrepInstruction, PrepOwner,
                     ProductAttribute, ProductQuantity, ShipmentLabels,
                     ShipmentListing, SkuEligibility, SkuIneligibilityReason,
                     SkuQuantity, TrackingDetails, TransportationDetails,
                     UpdateInboundRequest,
                     UpdateInboundShipmentTransportDetailsRequest,
                     VolumeUnitOfMeasurement, WeightUnitOfMeasurement)

__all__ = [
    "Address",
    "CarrierCode",
    "CarrierCodeType",
    "DestinationDetails",
    "DimensionUnitOfMeasurement",
    "DistributionPackage",
    "DistributionPackageContents",
    "DistributionPackageQuantity",
    "DistributionPackageType",
    "Error",
    "ErrorList",
    "InboundEligibility",
    "InboundEligibilityStatus",
    "InboundOrder",
    "InboundOrderCreationData",
    "InboundOrderReference",
    "InboundPackages",
    "InboundPreferences",
    "InboundShipment",
    "InboundShipmentStatus",
    "InboundShipmentSummary",
    "InboundStatus",
    "ExpirationDetails",
    "InventoryDetails",
    "InventoryListing",
    "InventoryQuantity",
    "InventorySummary",
    "InventoryUnitOfMeasurement",
    "LabelOwner",
    "LabelStatus",
    "MeasurementData",
    "OrderIneligibilityReason",
    "PackageDimensions",
    "PackageVolume",
    "PackageWeight",
    "PrepDetails",
    "PrepCategory",
    "PrepInstruction",
    "PrepOwner",
    "ProductAttribute",
    "ProductQuantity",
    "ShipmentLabels",
    "ShipmentListing",
    "SkuEligibility",
    "SkuIneligibilityReason",
    "SkuQuantity",
    "TrackingDetails",
    "TransportationDetails",
    "VolumeUnitOfMeasurement",
    "WeightUnitOfMeasurement",
    "CreateInboundRequest",
    "GetInboundRequest",
    "UpdateInboundRequest",
    "CancelInboundRequest",
    "ConfirmInboundRequest",
    "GetInboundShipmentRequest",
    "GetInboundShipmentLabelsRequest",
    "UpdateInboundShipmentTransportDetailsRequest",
    "CheckInboundEligibilityRequest",
    "ListInboundShipmentsRequest",
    "ListInventoryRequest",
]
