"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (AggregationFrequency, AutoEnrollmentPreference,
                     DiscountFunding, EligibilityStatus, EnrollmentMethod,
                     Error, ErrorList, GetSellingPartnerMetricsRequest,
                     GetSellingPartnerMetricsRequestBody,
                     GetSellingPartnerMetricsResponse,
                     GetSellingPartnerMetricsResponseMetric,
                     ListOfferMetricsRequest, ListOfferMetricsRequestBody,
                     ListOfferMetricsRequestFilters,
                     ListOfferMetricsRequestPagination,
                     ListOfferMetricsRequestSort, ListOfferMetricsResponse,
                     ListOfferMetricsResponseOffer, ListOfferMetricsSortKey,
                     ListOffersRequest, ListOffersRequestBody,
                     ListOffersRequestFilters, ListOffersRequestPagination,
                     ListOffersRequestSort, ListOffersResponse,
                     ListOffersResponseOffer, ListOffersSortKey, MarketplaceId,
                     Metric, OfferProgramConfiguration,
                     OfferProgramConfigurationPreferences,
                     OfferProgramConfigurationPromotions,
                     OfferProgramConfigurationPromotionsDiscountFunding,
                     PaginationResponse, Preference, ProgramType, ProgramTypes,
                     Promotion, SortOrder, TimeInterval, TimePeriodType)

__all__ = [
    "GetSellingPartnerMetricsRequestBody",
    "ListOfferMetricsRequestBody",
    "ListOffersRequestBody",
    "EligibilityStatus",
    "Preference",
    "Promotion",
    "DiscountFunding",
    "OfferProgramConfiguration",
    "OfferProgramConfigurationPreferences",
    "OfferProgramConfigurationPromotions",
    "OfferProgramConfigurationPromotionsDiscountFunding",
    "ListOfferMetricsRequestPagination",
    "AutoEnrollmentPreference",
    "ProgramTypes",
    "ProgramType",
    "EnrollmentMethod",
    "ListOfferMetricsRequestFilters",
    "ListOfferMetricsRequestSort",
    "ListOfferMetricsSortKey",
    "ListOffersRequestPagination",
    "ListOffersRequestFilters",
    "ListOffersRequestSort",
    "ListOffersSortKey",
    "MarketplaceId",
    "AggregationFrequency",
    "TimeInterval",
    "Metric",
    "SortOrder",
    "TimePeriodType",
    "GetSellingPartnerMetricsResponse",
    "GetSellingPartnerMetricsResponseMetric",
    "ListOfferMetricsResponse",
    "ListOffersResponse",
    "ListOffersResponseOffer",
    "PaginationResponse",
    "ListOfferMetricsResponseOffer",
    "ErrorList",
    "Error",
    "GetSellingPartnerMetricsRequest",
    "ListOfferMetricsRequest",
    "ListOffersRequest",
]
