# coding: utf-8

"""
    Selling Partner API for Notifications

    The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.event_bridge_resource_specification import EventBridgeResourceSpecification  # noqa: E501
from swagger_client.rest import ApiException


class TestEventBridgeResourceSpecification(unittest.TestCase):
    """EventBridgeResourceSpecification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventBridgeResourceSpecification(self):
        """Test EventBridgeResourceSpecification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.event_bridge_resource_specification.EventBridgeResourceSpecification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
