"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (AdditionalLocationInfo, Address, Amount,
                     CancelFulfillmentOrderRequest,
                     CancelFulfillmentOrderResponse, CODSettings,
                     CreateFulfillmentOrderItem,
                     CreateFulfillmentOrderItemList,
                     CreateFulfillmentOrderRequest,
                     CreateFulfillmentOrderRequestBody,
                     CreateFulfillmentOrderResponse,
                     CreateFulfillmentReturnRequest,
                     CreateFulfillmentReturnRequestBody,
                     CreateFulfillmentReturnResponse,
                     CreateFulfillmentReturnResult, CreateReturnItem,
                     CreateReturnItemList, CurrentStatus, DateRange, Decimal,
                     DeliveryDocument, DeliveryDocumentList,
                     DeliveryInformation, DeliveryMessage, DeliveryOffer,
                     DeliveryOffersList, DeliveryOffersRequest, DeliveryPolicy,
                     DeliveryPreferences, DeliveryWindow, DeliveryWindowList,
                     Destination, DropOffLocation, Error, ErrorList, EventCode,
                     Feature, Features, FeatureSettings, FeatureSku, Fee,
                     FeeList, FulfillmentAction, FulfillmentOrder,
                     FulfillmentOrderItem, FulfillmentOrderItemList,
                     FulfillmentOrderStatus, FulfillmentPolicy,
                     FulfillmentPreview, FulfillmentPreviewItem,
                     FulfillmentPreviewItemList, FulfillmentPreviewList,
                     FulfillmentPreviewShipment,
                     FulfillmentPreviewShipmentList,
                     FulfillmentReturnItemStatus, FulfillmentShipment,
                     FulfillmentShipmentItem, FulfillmentShipmentItemList,
                     FulfillmentShipmentList, FulfillmentShipmentPackage,
                     FulfillmentShipmentPackageList, GetDeliveryOffersProduct,
                     GetDeliveryOffersRequestBody, GetDeliveryOffersResponse,
                     GetDeliveryOffersResult, GetDeliveryOffersTerms,
                     GetFeatureInventoryRequest, GetFeatureInventoryResponse,
                     GetFeatureInventoryResult, GetFeatureSKURequest,
                     GetFeatureSkuResponse, GetFeatureSkuResult,
                     GetFeaturesRequest, GetFeaturesResponse,
                     GetFeaturesResult, GetFulfillmentOrderRequest,
                     GetFulfillmentOrderResponse, GetFulfillmentOrderResult,
                     GetFulfillmentPreviewItem, GetFulfillmentPreviewItemList,
                     GetFulfillmentPreviewRequest,
                     GetFulfillmentPreviewRequestBody,
                     GetFulfillmentPreviewResponse,
                     GetFulfillmentPreviewResult,
                     GetPackageTrackingDetailsRequest,
                     GetPackageTrackingDetailsResponse, InvalidItemReason,
                     InvalidItemReasonCode, InvalidReturnItem,
                     InvalidReturnItemList, IpAddress,
                     ListAllFulfillmentOrdersRequest,
                     ListAllFulfillmentOrdersResponse,
                     ListAllFulfillmentOrdersResult,
                     ListReturnReasonCodesRequest,
                     ListReturnReasonCodesResponse,
                     ListReturnReasonCodesResult, LockerDetails, Money,
                     NotificationEmailList, Origin, PackageTrackingDetails,
                     PaymentInformation, PaymentInformationList,
                     ProductIdentifier, Quantity, ReasonCodeDetails,
                     ReasonCodeDetailsList, ReturnAuthorization,
                     ReturnAuthorizationList, ReturnItem,
                     ReturnItemDisposition, ReturnItemList,
                     ScheduledDeliveryInfo, ShippingSpeedCategory,
                     ShippingSpeedCategoryList, StringList,
                     SubmitFulfillmentOrderStatusUpdateRequest,
                     SubmitFulfillmentOrderStatusUpdateRequestBody,
                     SubmitFulfillmentOrderStatusUpdateResponse, Timestamp,
                     TrackingAddress, TrackingEvent, TrackingEventList,
                     UnfulfillablePreviewItem, UnfulfillablePreviewItemList,
                     UpdateFulfillmentOrderItem,
                     UpdateFulfillmentOrderItemList,
                     UpdateFulfillmentOrderRequest,
                     UpdateFulfillmentOrderRequestBody,
                     UpdateFulfillmentOrderResponse, VariablePrecisionAddress,
                     Weight)

__all__ = [
    "Error",
    "ErrorList",
    "Address",
    "CODSettings",
    "CreateFulfillmentOrderItem",
    "CreateFulfillmentOrderItemList",
    "FulfillmentPolicy",
    "FulfillmentOrderStatus",
    "CreateFulfillmentOrderRequestBody",
    "CreateFulfillmentReturnRequestBody",
    "CreateFulfillmentReturnResult",
    "CreateFulfillmentReturnResponse",
    "CreateReturnItem",
    "CreateReturnItemList",
    "Money",
    "Decimal",
    "DeliveryWindow",
    "DeliveryWindowList",
    "DeliveryPreferences",
    "DropOffLocation",
    "Fee",
    "FeeList",
    "FulfillmentAction",
    "FulfillmentOrder",
    "FulfillmentOrderItem",
    "FulfillmentOrderItemList",
    "FulfillmentPreview",
    "FulfillmentPreviewItem",
    "FulfillmentPreviewItemList",
    "FulfillmentPreviewList",
    "FulfillmentPreviewShipment",
    "FulfillmentPreviewShipmentList",
    "FulfillmentReturnItemStatus",
    "FulfillmentShipment",
    "FulfillmentShipmentItem",
    "FulfillmentShipmentItemList",
    "FulfillmentShipmentList",
    "FulfillmentShipmentPackage",
    "FulfillmentShipmentPackageList",
    "GetFulfillmentOrderResult",
    "GetFulfillmentOrderResponse",
    "GetFulfillmentPreviewItem",
    "GetFulfillmentPreviewItemList",
    "GetFulfillmentPreviewRequestBody",
    "GetFulfillmentPreviewResult",
    "GetFulfillmentPreviewResponse",
    "GetDeliveryOffersRequestBody",
    "GetDeliveryOffersResponse",
    "GetDeliveryOffersResult",
    "DeliveryOffersList",
    "DeliveryOffer",
    "GetDeliveryOffersProduct",
    "Amount",
    "GetDeliveryOffersTerms",
    "IpAddress",
    "Destination",
    "ProductIdentifier",
    "Origin",
    "VariablePrecisionAddress",
    "DateRange",
    "DeliveryPolicy",
    "DeliveryMessage",
    "InvalidItemReasonCode",
    "InvalidItemReason",
    "InvalidReturnItem",
    "InvalidReturnItemList",
    "ListAllFulfillmentOrdersResult",
    "ListAllFulfillmentOrdersResponse",
    "ListReturnReasonCodesResult",
    "ListReturnReasonCodesResponse",
    "LockerDetails",
    "DeliveryInformation",
    "DeliveryDocumentList",
    "DeliveryDocument",
    "NotificationEmailList",
    "CurrentStatus",
    "AdditionalLocationInfo",
    "PackageTrackingDetails",
    "GetPackageTrackingDetailsResponse",
    "ReasonCodeDetails",
    "ReasonCodeDetailsList",
    "PaymentInformation",
    "ReturnAuthorization",
    "PaymentInformationList",
    "ReturnAuthorizationList",
    "ReturnItem",
    "ReturnItemDisposition",
    "ReturnItemList",
    "ScheduledDeliveryInfo",
    "ShippingSpeedCategoryList",
    "StringList",
    "Timestamp",
    "TrackingAddress",
    "EventCode",
    "TrackingEvent",
    "TrackingEventList",
    "UnfulfillablePreviewItem",
    "UnfulfillablePreviewItemList",
    "UpdateFulfillmentOrderItem",
    "UpdateFulfillmentOrderItemList",
    "UpdateFulfillmentOrderRequestBody",
    "UpdateFulfillmentOrderResponse",
    "CreateFulfillmentOrderResponse",
    "CancelFulfillmentOrderResponse",
    "Weight",
    "Quantity",
    "ShippingSpeedCategory",
    "GetFeatureInventoryResponse",
    "GetFeatureInventoryResult",
    "FeatureSku",
    "GetFeaturesResponse",
    "GetFeaturesResult",
    "Features",
    "Feature",
    "GetFeatureSkuResponse",
    "GetFeatureSkuResult",
    "FeatureSettings",
    "SubmitFulfillmentOrderStatusUpdateRequestBody",
    "SubmitFulfillmentOrderStatusUpdateResponse",
    "GetFulfillmentPreviewRequest",
    "DeliveryOffersRequest",
    "ListAllFulfillmentOrdersRequest",
    "CreateFulfillmentOrderRequest",
    "GetPackageTrackingDetailsRequest",
    "ListReturnReasonCodesRequest",
    "CreateFulfillmentReturnRequest",
    "GetFulfillmentOrderRequest",
    "UpdateFulfillmentOrderRequest",
    "CancelFulfillmentOrderRequest",
    "SubmitFulfillmentOrderStatusUpdateRequest",
    "GetFeaturesRequest",
    "GetFeatureInventoryRequest",
    "GetFeatureSKURequest",
]
