# coding: utf-8

"""
    Selling Partner API for Reports

    The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.  # noqa: E501

    OpenAPI spec version: 2020-09-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.get_report_document_response import GetReportDocumentResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetReportDocumentResponse(unittest.TestCase):
    """GetReportDocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetReportDocumentResponse(self):
        """Test GetReportDocumentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_report_document_response.GetReportDocumentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
