"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, AddressWithContact, ArchiveSupplySourceRequest,
                     ContactDetails, CreateSupplySourceRequest,
                     CreateSupplySourceRequestBody, CreateSupplySourceResponse,
                     CurbsidePickupConfiguration, DateTime, DeliveryChannel,
                     Duration, EmailAddress, Error, ErrorList,
                     GetSupplySourceRequest, GetSupplySourcesRequest,
                     GetSupplySourcesResponse, InStorePickupConfiguration,
                     NonNegativeInteger, OperatingHour, OperatingHours,
                     OperatingHoursByDay, OperationalConfiguration,
                     OutboundCapability, ParkingConfiguration, ParkingCostType,
                     ParkingSpotIdentificationType,
                     ParkingWithAddressConfiguration, PickupChannel,
                     ReturnLocation, ServicesCapability, SupplySource,
                     SupplySourceAlias, SupplySourceCapabilities,
                     SupplySourceCode, SupplySourceConfiguration,
                     SupplySourceId, SupplySourceList, SupplySourceStatus,
                     SupplySourceStatusReadOnly, ThroughputCap,
                     ThroughputConfig, ThroughputUnit, TimeUnit,
                     UpdateSupplySourceRequest, UpdateSupplySourceRequestBody,
                     UpdateSupplySourceStatusRequest,
                     UpdateSupplySourceStatusRequestBody)

__all__ = [
    "Error",
    "ErrorList",
    "GetSupplySourcesResponse",
    "UpdateSupplySourceStatusRequestBody",
    "CreateSupplySourceRequestBody",
    "CreateSupplySourceResponse",
    "UpdateSupplySourceRequestBody",
    "SupplySource",
    "SupplySourceConfiguration",
    "SupplySourceCapabilities",
    "SupplySourceList",
    "SupplySourceId",
    "SupplySourceCode",
    "SupplySourceAlias",
    "SupplySourceStatusReadOnly",
    "SupplySourceStatus",
    "OutboundCapability",
    "ServicesCapability",
    "PickupChannel",
    "ParkingConfiguration",
    "ParkingCostType",
    "ParkingSpotIdentificationType",
    "InStorePickupConfiguration",
    "CurbsidePickupConfiguration",
    "ParkingWithAddressConfiguration",
    "DeliveryChannel",
    "OperationalConfiguration",
    "Duration",
    "ThroughputConfig",
    "ReturnLocation",
    "AddressWithContact",
    "ContactDetails",
    "ThroughputCap",
    "OperatingHour",
    "OperatingHours",
    "ThroughputUnit",
    "OperatingHoursByDay",
    "TimeUnit",
    "NonNegativeInteger",
    "EmailAddress",
    "Address",
    "DateTime",
    "GetSupplySourcesRequest",
    "CreateSupplySourceRequest",
    "GetSupplySourceRequest",
    "UpdateSupplySourceRequest",
    "ArchiveSupplySourceRequest",
    "UpdateSupplySourceStatusRequest",
]
