"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, AddressExtendedFields, AmazonPrograms,
                     AssociatedItem, AssociationType,
                     AutomatedShippingSettings, BusinessHours,
                     BuyerCustomizedInfoDetail, BuyerInfo,
                     BuyerRequestedCancel, BuyerTaxInfo, BuyerTaxInformation,
                     ConfirmShipmentErrorResponse, ConfirmShipmentOrderItem,
                     ConfirmShipmentOrderItemsList, ConfirmShipmentRequest,
                     ConfirmShipmentRequestBody, ConstraintType,
                     DeliveryPreferences, EasyShipShipmentStatus,
                     ElectronicInvoiceStatus, Error, ErrorList, ExceptionDates,
                     FulfillmentInstruction, GetOrderAddressRequest,
                     GetOrderAddressResponse, GetOrderBuyerInfoRequest,
                     GetOrderBuyerInfoResponse, GetOrderItemsBuyerInfoRequest,
                     GetOrderItemsBuyerInfoResponse, GetOrderItemsRequest,
                     GetOrderItemsResponse, GetOrderRegulatedInfoRequest,
                     GetOrderRegulatedInfoResponse, GetOrderRequest,
                     GetOrderResponse, GetOrdersRequest, GetOrdersResponse,
                     ItemBuyerInfo, MarketplaceId, MarketplaceTaxInfo,
                     Measurement, Money, OpenInterval, OpenTimeInterval, Order,
                     OrderAddress, OrderBuyerInfo, OrderItem,
                     OrderItemBuyerInfo, OrderItemBuyerInfoList, OrderItemList,
                     OrderItems, OrderItemsBuyerInfoList, OrderItemsList,
                     OrderList, OrderRegulatedInfo, OrdersList,
                     OtherDeliveryAttributes, PackageDetail,
                     PackageReferenceId, PaymentExecutionDetailItem,
                     PaymentExecutionDetailItemList,
                     PaymentMethodDetailItemList, PointsGrantedDetail,
                     PreferredDeliveryTime, PrescriptionDetail,
                     ProductInfoDetail, PromotionIdList, RegulatedInformation,
                     RegulatedInformationField,
                     RegulatedOrderVerificationStatus, RejectionReason,
                     ShipmentStatus, ShippingConstraints, SubstitutionOption,
                     SubstitutionOptionList, SubstitutionPreferences,
                     TaxClassification, TaxCollection, TransparencyCode,
                     TransparencyCodeList, UpdateShipmentStatusErrorResponse,
                     UpdateShipmentStatusRequest,
                     UpdateShipmentStatusRequestBody,
                     UpdateVerificationStatusErrorResponse,
                     UpdateVerificationStatusRequest,
                     UpdateVerificationStatusRequestBody,
                     ValidVerificationDetail, VerificationDetails,
                     VerificationStatus)

__all__ = [
    "UpdateShipmentStatusRequestBody",
    "UpdateVerificationStatusRequestBody",
    "MarketplaceId",
    "ShipmentStatus",
    "OrderItems",
    "UpdateShipmentStatusErrorResponse",
    "UpdateVerificationStatusErrorResponse",
    "GetOrdersResponse",
    "GetOrderResponse",
    "GetOrderBuyerInfoResponse",
    "GetOrderRegulatedInfoResponse",
    "GetOrderAddressResponse",
    "GetOrderItemsResponse",
    "GetOrderItemsBuyerInfoResponse",
    "OrdersList",
    "OrderList",
    "Order",
    "OrderBuyerInfo",
    "OrderRegulatedInfo",
    "RegulatedOrderVerificationStatus",
    "RejectionReason",
    "PrescriptionDetail",
    "ValidVerificationDetail",
    "VerificationDetails",
    "VerificationStatus",
    "RegulatedInformation",
    "RegulatedInformationField",
    "OrderAddress",
    "Address",
    "AddressExtendedFields",
    "DeliveryPreferences",
    "PreferredDeliveryTime",
    "BusinessHours",
    "ExceptionDates",
    "OpenInterval",
    "OpenTimeInterval",
    "OtherDeliveryAttributes",
    "Money",
    "PaymentMethodDetailItemList",
    "PaymentExecutionDetailItemList",
    "PaymentExecutionDetailItem",
    "BuyerTaxInfo",
    "MarketplaceTaxInfo",
    "TaxClassification",
    "OrderItemsList",
    "OrderItemList",
    "OrderItem",
    "AmazonPrograms",
    "SubstitutionPreferences",
    "SubstitutionOptionList",
    "SubstitutionOption",
    "Measurement",
    "AssociatedItem",
    "AssociationType",
    "OrderItemsBuyerInfoList",
    "OrderItemBuyerInfoList",
    "OrderItemBuyerInfo",
    "PointsGrantedDetail",
    "ProductInfoDetail",
    "PromotionIdList",
    "BuyerCustomizedInfoDetail",
    "TaxCollection",
    "BuyerTaxInformation",
    "FulfillmentInstruction",
    "ShippingConstraints",
    "ConstraintType",
    "BuyerInfo",
    "ItemBuyerInfo",
    "AutomatedShippingSettings",
    "BuyerRequestedCancel",
    "EasyShipShipmentStatus",
    "ElectronicInvoiceStatus",
    "ConfirmShipmentRequestBody",
    "ConfirmShipmentErrorResponse",
    "PackageDetail",
    "ConfirmShipmentOrderItemsList",
    "ConfirmShipmentOrderItem",
    "TransparencyCodeList",
    "TransparencyCode",
    "PackageReferenceId",
    "ErrorList",
    "Error",
    "GetOrdersRequest",
    "GetOrderRequest",
    "GetOrderBuyerInfoRequest",
    "GetOrderAddressRequest",
    "GetOrderItemsRequest",
    "GetOrderItemsBuyerInfoRequest",
    "UpdateShipmentStatusRequest",
    "GetOrderRegulatedInfoRequest",
    "UpdateVerificationStatusRequest",
    "ConfirmShipmentRequest",
]
