"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, CarrierDetails, Carton, CartonReferenceDetails,
                     CollectFreightPickupDetails, ContainerIdentification,
                     ContainerItem, Containers, ContainerSequenceNumbers,
                     Decimal, Dimensions, Duration, Error, ErrorList, Expiry,
                     GetShipmentDetailsRequest, GetShipmentDetailsResponse,
                     GetShipmentLabels, GetShipmentLabelsRequest,
                     ImportDetails, InnerContainersDetails, Item, ItemDetails,
                     ItemQuantity, LabelData, Location, Money,
                     PackageItemDetails, PackedItems, PackedQuantity,
                     Pagination, Pallet, PartyIdentification,
                     PurchaseOrderItemDetails, PurchaseOrderItems,
                     PurchaseOrders, Route, Shipment, ShipmentConfirmation,
                     ShipmentDetails, ShipmentInformation,
                     ShipmentMeasurements, ShipmentStatusDetails, Stop,
                     SubmitShipmentConfirmationsRequest,
                     SubmitShipmentConfirmationsRequestBody,
                     SubmitShipmentConfirmationsResponse, SubmitShipments,
                     SubmitShipmentsRequest, TaxRegistrationDetails,
                     TotalWeight, TransactionReference, TransportationDetails,
                     TransportationDetailsForShipmentConfirmation,
                     TransportationLabels, TransportLabel,
                     TransportShipmentMeasurements, VendorDetails, Volume,
                     Weight)

__all__ = [
    "SubmitShipmentConfirmationsRequestBody",
    "SubmitShipments",
    "GetShipmentDetailsResponse",
    "GetShipmentLabels",
    "ShipmentDetails",
    "TransportationLabels",
    "Pagination",
    "ShipmentConfirmation",
    "Shipment",
    "TransportLabel",
    "ShipmentMeasurements",
    "ShipmentInformation",
    "LabelData",
    "VendorDetails",
    "ShipmentStatusDetails",
    "TransportShipmentMeasurements",
    "CollectFreightPickupDetails",
    "PurchaseOrders",
    "TransportationDetails",
    "TransportationDetailsForShipmentConfirmation",
    "CarrierDetails",
    "ImportDetails",
    "Containers",
    "PackedItems",
    "Item",
    "PurchaseOrderItems",
    "Carton",
    "InnerContainersDetails",
    "ContainerSequenceNumbers",
    "Pallet",
    "ItemDetails",
    "PackageItemDetails",
    "PurchaseOrderItemDetails",
    "ContainerIdentification",
    "ContainerItem",
    "CartonReferenceDetails",
    "PartyIdentification",
    "TaxRegistrationDetails",
    "Address",
    "Route",
    "Stop",
    "Location",
    "Dimensions",
    "Volume",
    "Weight",
    "Money",
    "Decimal",
    "ItemQuantity",
    "TotalWeight",
    "PackedQuantity",
    "Expiry",
    "Duration",
    "SubmitShipmentConfirmationsResponse",
    "TransactionReference",
    "ErrorList",
    "Error",
    "SubmitShipmentConfirmationsRequest",
    "SubmitShipmentsRequest",
    "GetShipmentDetailsRequest",
    "GetShipmentLabelsRequest",
]
