"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (AplusPaginatedResponse, AplusResponse, Asin, AsinBadge,
                     AsinBadgeSet, AsinMetadata, AsinMetadataSet, AsinSet,
                     ColorType, ContentBadge, ContentBadgeSet, ContentDocument,
                     ContentMetadata, ContentMetadataRecord,
                     ContentMetadataRecordList, ContentModule,
                     ContentModuleList, ContentModuleType, ContentRecord,
                     ContentReferenceKey, ContentReferenceKeySet,
                     ContentStatus, ContentSubType, ContentType,
                     CreateContentDocumentRequest, Decorator, DecoratorSet,
                     DecoratorType, Error, ErrorList,
                     GetContentDocumentRequest, GetContentDocumentResponse,
                     ImageComponent, ImageCropSpecification, ImageDimensions,
                     ImageOffsets, IntegerWithUnits, LanguageTag,
                     ListContentDocumentAsinRelationsRequest,
                     ListContentDocumentAsinRelationsResponse, MarketplaceId,
                     MessageSet, PageToken, ParagraphComponent, PlainTextItem,
                     PositionType,
                     PostContentDocumentApprovalSubmissionRequest,
                     PostContentDocumentApprovalSubmissionResponse,
                     PostContentDocumentAsinRelationsRequest,
                     PostContentDocumentAsinRelationsRequestBody,
                     PostContentDocumentAsinRelationsResponse,
                     PostContentDocumentRequestBody,
                     PostContentDocumentResponse,
                     PostContentDocumentSuspendSubmissionRequest,
                     PostContentDocumentSuspendSubmissionResponse,
                     PublishRecord, PublishRecordList,
                     SearchContentDocumentsRequest,
                     SearchContentDocumentsResponse,
                     SearchContentPublishRecordsRequest,
                     SearchContentPublishRecordsResponse,
                     StandardCompanyLogoModule, StandardComparisonProductBlock,
                     StandardComparisonTableModule,
                     StandardFourImageTextModule,
                     StandardFourImageTextQuadrantModule,
                     StandardHeaderImageTextModule,
                     StandardHeaderTextListBlock, StandardImageCaptionBlock,
                     StandardImageSidebarModule, StandardImageTextBlock,
                     StandardImageTextCaptionBlock,
                     StandardImageTextOverlayModule,
                     StandardMultipleImageTextModule,
                     StandardProductDescriptionModule,
                     StandardSingleImageHighlightsModule,
                     StandardSingleImageSpecsDetailModule,
                     StandardSingleSideImageModule, StandardTechSpecsModule,
                     StandardTextBlock, StandardTextListBlock,
                     StandardTextModule, StandardTextPairBlock,
                     StandardThreeImageTextModule, TextComponent, TextItem,
                     UpdateContentDocumentRequest,
                     ValidateContentDocumentAsinRelationsRequest,
                     ValidateContentDocumentAsinRelationsResponse)

__all__ = [
    "AplusResponse",
    "AplusPaginatedResponse",
    "ErrorList",
    "MessageSet",
    "Error",
    "ContentMetadataRecordList",
    "ContentMetadataRecord",
    "ContentMetadata",
    "ContentType",
    "ContentSubType",
    "ContentStatus",
    "ContentBadgeSet",
    "ContentBadge",
    "AsinBadgeSet",
    "AsinBadge",
    "MarketplaceId",
    "LanguageTag",
    "AsinSet",
    "Asin",
    "AsinMetadataSet",
    "AsinMetadata",
    "PublishRecordList",
    "PublishRecord",
    "ContentReferenceKeySet",
    "ContentReferenceKey",
    "PageToken",
    "ImageCropSpecification",
    "ImageDimensions",
    "ImageOffsets",
    "IntegerWithUnits",
    "ContentRecord",
    "ContentDocument",
    "ContentModuleList",
    "ContentModule",
    "ContentModuleType",
    "StandardCompanyLogoModule",
    "StandardComparisonTableModule",
    "StandardFourImageTextModule",
    "StandardFourImageTextQuadrantModule",
    "StandardHeaderImageTextModule",
    "StandardImageSidebarModule",
    "StandardImageTextOverlayModule",
    "StandardMultipleImageTextModule",
    "StandardProductDescriptionModule",
    "StandardSingleImageHighlightsModule",
    "StandardSingleImageSpecsDetailModule",
    "StandardSingleSideImageModule",
    "StandardTechSpecsModule",
    "StandardTextModule",
    "StandardThreeImageTextModule",
    "StandardComparisonProductBlock",
    "StandardHeaderTextListBlock",
    "StandardTextListBlock",
    "StandardImageTextCaptionBlock",
    "StandardImageCaptionBlock",
    "StandardImageTextBlock",
    "StandardTextBlock",
    "StandardTextPairBlock",
    "TextItem",
    "PlainTextItem",
    "ImageComponent",
    "ParagraphComponent",
    "TextComponent",
    "ColorType",
    "PositionType",
    "DecoratorSet",
    "Decorator",
    "DecoratorType",
    "SearchContentDocumentsResponse",
    "GetContentDocumentResponse",
    "PostContentDocumentRequestBody",
    "PostContentDocumentResponse",
    "ListContentDocumentAsinRelationsResponse",
    "PostContentDocumentAsinRelationsRequestBody",
    "PostContentDocumentAsinRelationsResponse",
    "ValidateContentDocumentAsinRelationsResponse",
    "SearchContentPublishRecordsResponse",
    "PostContentDocumentApprovalSubmissionResponse",
    "PostContentDocumentSuspendSubmissionResponse",
    "SearchContentDocumentsRequest",
    "CreateContentDocumentRequest",
    "GetContentDocumentRequest",
    "UpdateContentDocumentRequest",
    "ListContentDocumentAsinRelationsRequest",
    "PostContentDocumentAsinRelationsRequest",
    "ValidateContentDocumentAsinRelationsRequest",
    "SearchContentPublishRecordsRequest",
    "PostContentDocumentApprovalSubmissionRequest",
    "PostContentDocumentSuspendSubmissionRequest",
]
