"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (BrandRefinement, ClassificationRefinement, Dimension,
                     Dimensions, Error, ErrorList, GetCatalogItemRequest, Item,
                     ItemAsin, ItemAttributes, ItemBrowseClassification,
                     ItemBrowseClassifications,
                     ItemBrowseClassificationsByMarketplace,
                     ItemClassificationSalesRank, ItemContributor,
                     ItemContributorRole, ItemDimensions,
                     ItemDimensionsByMarketplace, ItemDisplayGroupSalesRank,
                     ItemIdentifier, ItemIdentifiers,
                     ItemIdentifiersByMarketplace, ItemImage, ItemImages,
                     ItemImagesByMarketplace, ItemProductTypeByMarketplace,
                     ItemProductTypes, ItemRelationship, ItemRelationships,
                     ItemRelationshipsByMarketplace, ItemSalesRanks,
                     ItemSalesRanksByMarketplace, ItemSearchResults,
                     ItemSummaries, ItemSummaryByMarketplace,
                     ItemVariationTheme, ItemVendorDetails,
                     ItemVendorDetailsByMarketplace, ItemVendorDetailsCategory,
                     Pagination, Refinements, SearchCatalogItemsRequest)

__all__ = [
    "Error",
    "ErrorList",
    "Item",
    "ItemAsin",
    "ItemAttributes",
    "ItemBrowseClassification",
    "ItemContributor",
    "ItemContributorRole",
    "ItemBrowseClassifications",
    "ItemBrowseClassificationsByMarketplace",
    "Dimension",
    "Dimensions",
    "ItemDimensions",
    "ItemDimensionsByMarketplace",
    "ItemIdentifiers",
    "ItemIdentifiersByMarketplace",
    "ItemIdentifier",
    "ItemImages",
    "ItemImagesByMarketplace",
    "ItemImage",
    "ItemProductTypes",
    "ItemProductTypeByMarketplace",
    "ItemSalesRanks",
    "ItemSalesRanksByMarketplace",
    "ItemClassificationSalesRank",
    "ItemDisplayGroupSalesRank",
    "ItemSummaries",
    "ItemSummaryByMarketplace",
    "ItemVariationTheme",
    "ItemRelationships",
    "ItemRelationshipsByMarketplace",
    "ItemRelationship",
    "ItemVendorDetailsCategory",
    "ItemVendorDetails",
    "ItemVendorDetailsByMarketplace",
    "ItemSearchResults",
    "Pagination",
    "Refinements",
    "BrandRefinement",
    "ClassificationRefinement",
    "SearchCatalogItemsRequest",
    "GetCatalogItemRequest",
]
