"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (AddAppointmentForServiceJobByServiceJobIdRequest,
                     AddAppointmentRequestBody, Address, Appointment,
                     AppointmentId, AppointmentResource, AppointmentResources,
                     AppointmentSlot, AppointmentSlotReport, AppointmentTime,
                     AppointmentTimeInput, AssignAppointmentResourcesRequest,
                     AssignAppointmentResourcesRequestBody,
                     AssignAppointmentResourcesResponse, AssociatedItem,
                     AvailabilityRecord, AvailabilityRecords, Buyer,
                     CancelReservationRequest, CancelReservationResponse,
                     CancelServiceJobByServiceJobIdRequest,
                     CancelServiceJobByServiceJobIdResponse, CapacityType,
                     CompleteServiceJobByServiceJobIdRequest,
                     CompleteServiceJobByServiceJobIdResponse,
                     CreateReservationRecord, CreateReservationRequest,
                     CreateReservationRequestBody, CreateReservationResponse,
                     CreateServiceDocumentUploadDestination,
                     CreateServiceDocumentUploadDestinationRequest,
                     DateTimeRange, DayOfWeek, EncryptionDetails, Error,
                     ErrorList, FixedSlot, FixedSlotCapacity,
                     FixedSlotCapacityErrors, FixedSlotCapacityQuery,
                     FulfillmentDocument, FulfillmentDocuments,
                     FulfillmentTime, GetAppointmentSlotsRequest,
                     GetAppointmentSlotsResponse,
                     GetAppointmmentSlotsByJobIdRequest,
                     GetFixedSlotCapacityRequest, GetRangeSlotCapacityRequest,
                     GetServiceJobByServiceJobIdRequest,
                     GetServiceJobByServiceJobIdResponse,
                     GetServiceJobsRequest, GetServiceJobsResponse,
                     ItemDelivery, ItemDeliveryPromise, JobListing, OrderId,
                     Poa, RangeCapacity, RangeSlot, RangeSlotCapacity,
                     RangeSlotCapacityErrors, RangeSlotCapacityQuery,
                     Recurrence,
                     RescheduleAppointmentForServiceJobByServiceJobIdRequest,
                     RescheduleAppointmentRequestBody, RescheduleReasonCode,
                     Reservation, ScopeOfWork, Seller,
                     ServiceDocumentUploadDestination, ServiceJob,
                     ServiceJobId, ServiceJobProvider, ServiceLocation,
                     ServiceUploadDocument,
                     SetAppointmentFulfillmentDataRequest,
                     SetAppointmentFulfillmentDataRequestBody,
                     SetAppointmentResponse, Technician,
                     UpdateReservationRecord, UpdateReservationRequest,
                     UpdateReservationRequestBody, UpdateReservationResponse,
                     UpdateScheduleRecord, UpdateScheduleRequest,
                     UpdateScheduleRequestBody, UpdateScheduleResponse,
                     Warning, WarningList)

__all__ = [
    "GetServiceJobByServiceJobIdResponse",
    "CancelServiceJobByServiceJobIdResponse",
    "CompleteServiceJobByServiceJobIdResponse",
    "GetServiceJobsResponse",
    "SetAppointmentResponse",
    "AssignAppointmentResourcesResponse",
    "AssignAppointmentResourcesRequestBody",
    "JobListing",
    "ServiceJob",
    "ServiceJobId",
    "OrderId",
    "ScopeOfWork",
    "Seller",
    "ServiceJobProvider",
    "Buyer",
    "AppointmentTime",
    "AppointmentId",
    "Appointment",
    "Technician",
    "Poa",
    "AssociatedItem",
    "ItemDelivery",
    "ItemDeliveryPromise",
    "ServiceLocation",
    "Address",
    "AddAppointmentRequestBody",
    "RescheduleAppointmentRequestBody",
    "AppointmentTimeInput",
    "RescheduleReasonCode",
    "ErrorList",
    "Error",
    "WarningList",
    "Warning",
    "RangeSlotCapacityErrors",
    "RangeSlotCapacity",
    "RangeCapacity",
    "RangeSlot",
    "FixedSlotCapacityErrors",
    "FixedSlotCapacity",
    "FixedSlot",
    "UpdateScheduleResponse",
    "SetAppointmentFulfillmentDataRequestBody",
    "FulfillmentTime",
    "DateTimeRange",
    "FulfillmentDocuments",
    "FulfillmentDocument",
    "AppointmentResources",
    "AppointmentResource",
    "CreateReservationResponse",
    "UpdateReservationResponse",
    "CancelReservationResponse",
    "DayOfWeek",
    "Recurrence",
    "AvailabilityRecord",
    "AvailabilityRecords",
    "Reservation",
    "UpdateScheduleRecord",
    "CreateReservationRecord",
    "UpdateReservationRecord",
    "RangeSlotCapacityQuery",
    "FixedSlotCapacityQuery",
    "UpdateScheduleRequestBody",
    "CapacityType",
    "CreateReservationRequestBody",
    "UpdateReservationRequestBody",
    "GetAppointmentSlotsResponse",
    "AppointmentSlotReport",
    "AppointmentSlot",
    "ServiceUploadDocument",
    "CreateServiceDocumentUploadDestination",
    "ServiceDocumentUploadDestination",
    "EncryptionDetails",
    "GetServiceJobByServiceJobIdRequest",
    "CancelServiceJobByServiceJobIdRequest",
    "CompleteServiceJobByServiceJobIdRequest",
    "GetServiceJobsRequest",
    "AddAppointmentForServiceJobByServiceJobIdRequest",
    "RescheduleAppointmentForServiceJobByServiceJobIdRequest",
    "AssignAppointmentResourcesRequest",
    "SetAppointmentFulfillmentDataRequest",
    "GetRangeSlotCapacityRequest",
    "GetFixedSlotCapacityRequest",
    "UpdateScheduleRequest",
    "CreateReservationRequest",
    "UpdateReservationRequest",
    "CancelReservationRequest",
    "GetAppointmmentSlotsByJobIdRequest",
    "GetAppointmentSlotsRequest",
    "CreateServiceDocumentUploadDestinationRequest",
]
