"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, CarrierId, Container, ContainerLabel,
                     ContainerLabelFormat, CreateContainerLabelRequest,
                     CreateContainerLabelRequestBody,
                     CreateContainerLabelResponse, CreateShippingLabelsRequest,
                     CreateShippingLabelsRequestBody, CustomerInvoice,
                     CustomerInvoiceList, Decimal, Dimensions, Error,
                     ErrorList, GetCustomerInvoiceRequest,
                     GetCustomerInvoicesRequest, GetPackingSlipRequest,
                     GetPackingSlipsRequest, GetShippingLabelRequest,
                     GetShippingLabelsRequest, Item, ItemQuantity, LabelData,
                     Package, Packages, PackedItem, PackingSlip,
                     PackingSlipList, Pagination, PartyIdentification,
                     ShipmentConfirmation, ShipmentDetails, ShipmentSchedule,
                     ShipmentStatusUpdate, ShippingLabel, ShippingLabelList,
                     ShippingLabelRequestBody, StatusUpdateDetails,
                     SubmitShipmentConfirmationsRequest,
                     SubmitShipmentConfirmationsRequestBody,
                     SubmitShipmentStatusUpdatesRequest,
                     SubmitShipmentStatusUpdatesRequestBody,
                     SubmitShippingLabelRequestBodyRequest,
                     SubmitShippingLabelsRequestBody, TaxRegistrationDetails,
                     TransactionReference, VendorContainerId, Weight)

__all__ = [
    "PackingSlip",
    "PackingSlipList",
    "CreateShippingLabelsRequestBody",
    "SubmitShippingLabelsRequestBody",
    "ShippingLabelRequestBody",
    "Item",
    "PackedItem",
    "PartyIdentification",
    "ShipmentDetails",
    "StatusUpdateDetails",
    "TaxRegistrationDetails",
    "Address",
    "ShipmentSchedule",
    "Dimensions",
    "Weight",
    "Decimal",
    "ItemQuantity",
    "ShippingLabelList",
    "LabelData",
    "ShippingLabel",
    "SubmitShipmentConfirmationsRequestBody",
    "ShipmentConfirmation",
    "SubmitShipmentStatusUpdatesRequestBody",
    "ShipmentStatusUpdate",
    "CustomerInvoiceList",
    "Pagination",
    "CustomerInvoice",
    "TransactionReference",
    "ErrorList",
    "Error",
    "Container",
    "CreateContainerLabelRequestBody",
    "Packages",
    "Package",
    "VendorContainerId",
    "CarrierId",
    "CreateContainerLabelResponse",
    "ContainerLabel",
    "ContainerLabelFormat",
    "GetShippingLabelsRequest",
    "SubmitShippingLabelRequestBodyRequest",
    "GetShippingLabelRequest",
    "CreateShippingLabelsRequest",
    "SubmitShipmentConfirmationsRequest",
    "SubmitShipmentStatusUpdatesRequest",
    "GetCustomerInvoicesRequest",
    "GetCustomerInvoiceRequest",
    "GetPackingSlipsRequest",
    "GetPackingSlipRequest",
    "CreateContainerLabelRequest",
]
