"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, AddressInput, AllOwnersConstraint,
                     AppointmentSlot, AppointmentSlotTime, Box,
                     BoxContentInformationSource, BoxInput, BoxRequirements,
                     BoxUpdateInput, CancelInboundPlanRequest,
                     CancelInboundPlanResponse,
                     CancelSelfShipAppointmentRequest,
                     CancelSelfShipAppointmentRequestBody,
                     CancelSelfShipAppointmentResponse, Carrier,
                     CarrierAppointment, ComplianceDetail,
                     ConfirmDeliveryWindowOptionsRequest,
                     ConfirmDeliveryWindowOptionsResponse,
                     ConfirmPackingOptionRequest, ConfirmPackingOptionResponse,
                     ConfirmPlacementOptionRequest,
                     ConfirmPlacementOptionResponse,
                     ConfirmShipmentContentUpdatePreviewRequest,
                     ConfirmShipmentContentUpdatePreviewResponse,
                     ConfirmTransportationOptionsRequest,
                     ConfirmTransportationOptionsRequestBody,
                     ConfirmTransportationOptionsResponse, ContactInformation,
                     ContentUpdatePreview, CreateInboundPlanRequest,
                     CreateInboundPlanRequestBody, CreateInboundPlanResponse,
                     CreateMarketplaceItemLabelsRequest,
                     CreateMarketplaceItemLabelsRequestBody,
                     CreateMarketplaceItemLabelsResponse, Currency,
                     CustomPlacementInput, Dates, DeliveryWindowOption,
                     Dimensions, DocumentDownload, Error, ErrorList,
                     FreightInformation, GenerateDeliveryWindowOptionsRequest,
                     GenerateDeliveryWindowOptionsResponse,
                     GeneratePackingOptionsRequest,
                     GeneratePackingOptionsResponse,
                     GeneratePlacementOptionsRequest,
                     GeneratePlacementOptionsRequestBody,
                     GeneratePlacementOptionsResponse,
                     GenerateSelfShipAppointmentSlotsRequest,
                     GenerateSelfShipAppointmentSlotsRequestBody,
                     GenerateSelfShipAppointmentSlotsResponse,
                     GenerateShipmentContentUpdatePreviewsRequest,
                     GenerateShipmentContentUpdatePreviewsRequestBody,
                     GenerateShipmentContentUpdatePreviewsResponse,
                     GenerateTransportationOptionsRequest,
                     GenerateTransportationOptionsRequestBody,
                     GenerateTransportationOptionsResponse,
                     GetDeliveryChallanDocumentRequest,
                     GetDeliveryChallanDocumentResponse,
                     GetInboundOperationStatusRequest, GetInboundPlanRequest,
                     GetSelfShipAppointmentSlotsRequest,
                     GetSelfShipAppointmentSlotsResponse,
                     GetShipmentContentUpdatePreviewRequest,
                     GetShipmentRequest, InboundOperationStatus, InboundPlan,
                     InboundPlanSummary, Incentive, Item, ItemInput,
                     ItemLabelPageType, LabelOwner, LabelPrintType,
                     ListDeliveryWindowOptionsRequest,
                     ListDeliveryWindowOptionsResponse,
                     ListInboundPlanBoxesRequest, ListInboundPlanBoxesResponse,
                     ListInboundPlanItemsRequest, ListInboundPlanItemsResponse,
                     ListInboundPlanPalletsRequest,
                     ListInboundPlanPalletsResponse, ListInboundPlansRequest,
                     ListInboundPlansResponse,
                     ListItemComplianceDetailsRequest,
                     ListItemComplianceDetailsResponse,
                     ListPackingGroupBoxesRequest,
                     ListPackingGroupBoxesResponse,
                     ListPackingGroupItemsRequest,
                     ListPackingGroupItemsResponse, ListPackingOptionsRequest,
                     ListPackingOptionsResponse, ListPlacementOptionsRequest,
                     ListPlacementOptionsResponse, ListPrepDetailsRequest,
                     ListPrepDetailsResponse, ListShipmentBoxesRequest,
                     ListShipmentBoxesResponse,
                     ListShipmentContentUpdatePreviewsRequest,
                     ListShipmentContentUpdatePreviewsResponse,
                     ListShipmentItemsRequest, ListShipmentItemsResponse,
                     ListShipmentPalletsRequest, ListShipmentPalletsResponse,
                     ListTransportationOptionsRequest,
                     ListTransportationOptionsResponse, LtlTrackingDetail,
                     LtlTrackingDetailInput, MskuPrepDetail,
                     MskuPrepDetailInput, MskuQuantity, OperationProblem,
                     OperationStatus, OwnerConstraint, PackageGroupingInput,
                     PackingConfiguration, PackingOption, PackingOptionSummary,
                     Pagination, Pallet, PalletInput, PlacementOption,
                     PlacementOptionSummary, PrepCategory, PrepInstruction,
                     PrepOwner, PrepType, Quote, ReasonComment, Region,
                     RequestedUpdates, ScheduleSelfShipAppointmentRequest,
                     ScheduleSelfShipAppointmentRequestBody,
                     ScheduleSelfShipAppointmentResponse,
                     SelectedDeliveryWindow, SelfShipAppointmentDetails,
                     SelfShipAppointmentSlotsAvailability,
                     SetPackingInformationRequest,
                     SetPackingInformationRequestBody,
                     SetPackingInformationResponse, SetPrepDetailsRequest,
                     SetPrepDetailsRequestBody, SetPrepDetailsResponse,
                     Shipment, ShipmentDestination, ShipmentSource,
                     ShipmentSummary, ShipmentTransportationConfiguration,
                     ShippingConfiguration, ShippingRequirements,
                     SpdTrackingDetail, SpdTrackingDetailInput,
                     SpdTrackingItem, SpdTrackingItemInput, Stackability,
                     TaxDetails, TaxRate, TrackingDetails,
                     TrackingDetailsInput, TransportationOption,
                     TransportationSelection, UnitOfMeasurement, UnitOfWeight,
                     UpdateInboundPlanNameRequest,
                     UpdateInboundPlanNameRequestBody,
                     UpdateItemComplianceDetailsRequest,
                     UpdateItemComplianceDetailsRequestBody,
                     UpdateItemComplianceDetailsResponse,
                     UpdateShipmentNameRequest, UpdateShipmentNameRequestBody,
                     UpdateShipmentSourceAddressRequest,
                     UpdateShipmentSourceAddressRequestBody,
                     UpdateShipmentSourceAddressResponse,
                     UpdateShipmentTrackingDetailsRequest,
                     UpdateShipmentTrackingDetailsRequestBody,
                     UpdateShipmentTrackingDetailsResponse, Weight,
                     WeightRange, Window, WindowInput)

__all__ = [
    "Address",
    "AddressInput",
    "AllOwnersConstraint",
    "AppointmentSlot",
    "AppointmentSlotTime",
    "Box",
    "BoxContentInformationSource",
    "BoxInput",
    "BoxRequirements",
    "BoxUpdateInput",
    "CancelInboundPlanResponse",
    "CancelSelfShipAppointmentRequestBody",
    "CancelSelfShipAppointmentResponse",
    "Carrier",
    "CarrierAppointment",
    "ComplianceDetail",
    "ConfirmDeliveryWindowOptionsResponse",
    "ConfirmPackingOptionResponse",
    "ConfirmPlacementOptionResponse",
    "ConfirmShipmentContentUpdatePreviewResponse",
    "ConfirmTransportationOptionsRequestBody",
    "ConfirmTransportationOptionsResponse",
    "ContactInformation",
    "ContentUpdatePreview",
    "CreateInboundPlanRequestBody",
    "CreateInboundPlanResponse",
    "CreateMarketplaceItemLabelsRequestBody",
    "CreateMarketplaceItemLabelsResponse",
    "Currency",
    "CustomPlacementInput",
    "Dates",
    "DeliveryWindowOption",
    "Dimensions",
    "DocumentDownload",
    "Error",
    "ErrorList",
    "FreightInformation",
    "GenerateDeliveryWindowOptionsResponse",
    "GeneratePackingOptionsResponse",
    "GeneratePlacementOptionsRequestBody",
    "GeneratePlacementOptionsResponse",
    "GenerateSelfShipAppointmentSlotsRequestBody",
    "GenerateSelfShipAppointmentSlotsResponse",
    "GenerateShipmentContentUpdatePreviewsRequestBody",
    "GenerateShipmentContentUpdatePreviewsResponse",
    "GenerateTransportationOptionsRequestBody",
    "GenerateTransportationOptionsResponse",
    "GetDeliveryChallanDocumentResponse",
    "GetSelfShipAppointmentSlotsResponse",
    "InboundOperationStatus",
    "InboundPlan",
    "InboundPlanSummary",
    "Incentive",
    "Item",
    "ItemInput",
    "ItemLabelPageType",
    "LabelOwner",
    "LabelPrintType",
    "ListDeliveryWindowOptionsResponse",
    "ListInboundPlanBoxesResponse",
    "ListInboundPlanItemsResponse",
    "ListInboundPlanPalletsResponse",
    "ListInboundPlansResponse",
    "ListItemComplianceDetailsResponse",
    "ListPackingGroupBoxesResponse",
    "ListPackingGroupItemsResponse",
    "ListPackingOptionsResponse",
    "ListPlacementOptionsResponse",
    "ListPrepDetailsResponse",
    "ListShipmentBoxesResponse",
    "ListShipmentContentUpdatePreviewsResponse",
    "ListShipmentItemsResponse",
    "ListShipmentPalletsResponse",
    "ListTransportationOptionsResponse",
    "LtlTrackingDetail",
    "LtlTrackingDetailInput",
    "MskuPrepDetail",
    "MskuPrepDetailInput",
    "MskuQuantity",
    "OperationProblem",
    "OperationStatus",
    "OwnerConstraint",
    "PackageGroupingInput",
    "PackingConfiguration",
    "PackingOption",
    "PackingOptionSummary",
    "Pagination",
    "Pallet",
    "PalletInput",
    "PlacementOption",
    "PlacementOptionSummary",
    "PrepCategory",
    "PrepInstruction",
    "PrepOwner",
    "PrepType",
    "Quote",
    "ReasonComment",
    "Region",
    "RequestedUpdates",
    "ScheduleSelfShipAppointmentRequestBody",
    "ScheduleSelfShipAppointmentResponse",
    "SelectedDeliveryWindow",
    "SelfShipAppointmentDetails",
    "SelfShipAppointmentSlotsAvailability",
    "SetPackingInformationRequestBody",
    "SetPackingInformationResponse",
    "SetPrepDetailsRequestBody",
    "SetPrepDetailsResponse",
    "Shipment",
    "ShipmentDestination",
    "ShipmentSource",
    "ShipmentSummary",
    "ShipmentTransportationConfiguration",
    "ShippingConfiguration",
    "ShippingRequirements",
    "SpdTrackingDetail",
    "SpdTrackingDetailInput",
    "SpdTrackingItem",
    "SpdTrackingItemInput",
    "Stackability",
    "TaxDetails",
    "TaxRate",
    "TrackingDetails",
    "TrackingDetailsInput",
    "TransportationOption",
    "TransportationSelection",
    "UnitOfMeasurement",
    "UnitOfWeight",
    "UpdateInboundPlanNameRequestBody",
    "UpdateItemComplianceDetailsRequestBody",
    "UpdateItemComplianceDetailsResponse",
    "UpdateShipmentNameRequestBody",
    "UpdateShipmentSourceAddressRequestBody",
    "UpdateShipmentSourceAddressResponse",
    "UpdateShipmentTrackingDetailsRequestBody",
    "UpdateShipmentTrackingDetailsResponse",
    "Weight",
    "WeightRange",
    "Window",
    "WindowInput",
    "ListInboundPlansRequest",
    "CreateInboundPlanRequest",
    "GetInboundPlanRequest",
    "ListInboundPlanBoxesRequest",
    "CancelInboundPlanRequest",
    "ListInboundPlanItemsRequest",
    "UpdateInboundPlanNameRequest",
    "ListPackingGroupBoxesRequest",
    "ListPackingGroupItemsRequest",
    "SetPackingInformationRequest",
    "ListPackingOptionsRequest",
    "GeneratePackingOptionsRequest",
    "ConfirmPackingOptionRequest",
    "ListInboundPlanPalletsRequest",
    "ListPlacementOptionsRequest",
    "GeneratePlacementOptionsRequest",
    "ConfirmPlacementOptionRequest",
    "GetShipmentRequest",
    "ListShipmentBoxesRequest",
    "ListShipmentContentUpdatePreviewsRequest",
    "GenerateShipmentContentUpdatePreviewsRequest",
    "GetShipmentContentUpdatePreviewRequest",
    "ConfirmShipmentContentUpdatePreviewRequest",
    "GetDeliveryChallanDocumentRequest",
    "ListDeliveryWindowOptionsRequest",
    "GenerateDeliveryWindowOptionsRequest",
    "ConfirmDeliveryWindowOptionsRequest",
    "ListShipmentItemsRequest",
    "UpdateShipmentNameRequest",
    "ListShipmentPalletsRequest",
    "CancelSelfShipAppointmentRequest",
    "GetSelfShipAppointmentSlotsRequest",
    "GenerateSelfShipAppointmentSlotsRequest",
    "ScheduleSelfShipAppointmentRequest",
    "UpdateShipmentSourceAddressRequest",
    "UpdateShipmentTrackingDetailsRequest",
    "ListTransportationOptionsRequest",
    "GenerateTransportationOptionsRequest",
    "ConfirmTransportationOptionsRequest",
    "ListItemComplianceDetailsRequest",
    "UpdateItemComplianceDetailsRequest",
    "CreateMarketplaceItemLabelsRequest",
    "ListPrepDetailsRequest",
    "SetPrepDetailsRequest",
    "GetInboundOperationStatusRequest",
]
