"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Asin, BatchRequestBody, BatchResponse,
                     CompetitiveSummaryBatchRequestBody,
                     CompetitiveSummaryBatchResponse,
                     CompetitiveSummaryIncludedData,
                     CompetitiveSummaryRequestBody,
                     CompetitiveSummaryRequestList, CompetitiveSummaryResponse,
                     CompetitiveSummaryResponseBody,
                     CompetitiveSummaryResponseList, Condition, Error,
                     ErrorList, Errors, FeaturedBuyingOption, FeaturedOffer,
                     FeaturedOfferExpectedPrice,
                     FeaturedOfferExpectedPriceRequestBody,
                     FeaturedOfferExpectedPriceRequestList,
                     FeaturedOfferExpectedPriceRequestParams,
                     FeaturedOfferExpectedPriceResponse,
                     FeaturedOfferExpectedPriceResponseBody,
                     FeaturedOfferExpectedPriceResponseList,
                     FeaturedOfferExpectedPriceResult,
                     FeaturedOfferExpectedPriceResultList,
                     FeaturedOfferSegment, FulfillmentType,
                     GetCompetitiveSummaryRequest,
                     GetFeaturedOfferExpectedPriceBatchRequest,
                     GetFeaturedOfferExpectedPriceBatchRequestBody,
                     GetFeaturedOfferExpectedPriceBatchResponse, HttpBody,
                     HttpHeaders, HttpMethod, HttpStatusLine, HttpUri,
                     LowestPricedOffer, LowestPricedOffersInput, MarketplaceId,
                     MoneyType, Offer, OfferIdentifier, Points, PostalCode,
                     Price, PrimeDetails, ReferencePrice, SampleLocation,
                     Segment, SegmentDetails, SegmentedFeaturedOffer,
                     ShippingOption, Sku)

__all__ = [
    "GetFeaturedOfferExpectedPriceBatchRequestBody",
    "FeaturedOfferExpectedPriceRequestList",
    "FeaturedOfferExpectedPriceRequestBody",
    "FeaturedOfferExpectedPriceRequestParams",
    "GetFeaturedOfferExpectedPriceBatchResponse",
    "FeaturedOfferExpectedPriceResponseList",
    "FeaturedOfferExpectedPriceResponse",
    "CompetitiveSummaryBatchRequestBody",
    "CompetitiveSummaryRequestList",
    "CompetitiveSummaryRequestBody",
    "CompetitiveSummaryIncludedData",
    "LowestPricedOffersInput",
    "CompetitiveSummaryBatchResponse",
    "CompetitiveSummaryResponseList",
    "CompetitiveSummaryResponse",
    "CompetitiveSummaryResponseBody",
    "ReferencePrice",
    "FeaturedBuyingOption",
    "SegmentedFeaturedOffer",
    "LowestPricedOffer",
    "Offer",
    "PrimeDetails",
    "ShippingOption",
    "FeaturedOfferSegment",
    "SegmentDetails",
    "SampleLocation",
    "PostalCode",
    "Errors",
    "FeaturedOfferExpectedPriceResponseBody",
    "FeaturedOfferExpectedPriceResultList",
    "FeaturedOfferExpectedPriceResult",
    "FeaturedOfferExpectedPrice",
    "FeaturedOffer",
    "HttpHeaders",
    "HttpStatusLine",
    "HttpBody",
    "HttpUri",
    "HttpMethod",
    "BatchRequestBody",
    "BatchResponse",
    "OfferIdentifier",
    "MoneyType",
    "Price",
    "Points",
    "FulfillmentType",
    "MarketplaceId",
    "Sku",
    "Segment",
    "Condition",
    "Asin",
    "ErrorList",
    "Error",
    "GetFeaturedOfferExpectedPriceBatchRequest",
    "GetCompetitiveSummaryRequest",
]
