# coding: utf-8

"""
    Selling Partner API for Orders

    The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.payment_execution_detail_item_list import PaymentExecutionDetailItemList  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentExecutionDetailItemList(unittest.TestCase):
    """PaymentExecutionDetailItemList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentExecutionDetailItemList(self):
        """Test PaymentExecutionDetailItemList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.payment_execution_detail_item_list.PaymentExecutionDetailItemList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
