# coding: utf-8

"""
    Selling Partner API for Orders

    The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.get_order_response import GetOrderResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetOrderResponse(unittest.TestCase):
    """GetOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOrderResponse(self):
        """Test GetOrderResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_order_response.GetOrderResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
