"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, Container, CustomerInvoice, CustomerInvoiceList,
                     Decimal, Dimensions, Error, ErrorList,
                     GetCustomerInvoiceRequest, GetCustomerInvoiceResponse,
                     GetCustomerInvoicesRequest, GetCustomerInvoicesResponse,
                     GetPackingSlipListResponse, GetPackingSlipRequest,
                     GetPackingSlipResponse, GetPackingSlipsRequest,
                     GetShippingLabelListResponse, GetShippingLabelRequest,
                     GetShippingLabelResponse, GetShippingLabelsRequest, Item,
                     ItemQuantity, LabelData, PackedItem, PackingSlip,
                     PackingSlipList, Pagination, PartyIdentification,
                     ShipmentConfirmation, ShipmentDetails,
                     ShipmentStatusUpdate, ShippingLabel, ShippingLabelList,
                     ShippingLabelRequestBody, StatusUpdateDetails,
                     SubmitShipmentConfirmationsRequest,
                     SubmitShipmentConfirmationsRequestBody,
                     SubmitShipmentConfirmationsResponse,
                     SubmitShipmentStatusUpdatesRequest,
                     SubmitShipmentStatusUpdatesRequestBody,
                     SubmitShipmentStatusUpdatesResponse,
                     SubmitShippingLabelRequestBodyRequest,
                     SubmitShippingLabelsRequestBody,
                     SubmitShippingLabelsResponse, TaxRegistrationDetails,
                     TransactionReference, Weight)

__all__ = [
    "PackingSlip",
    "PackingSlipList",
    "GetPackingSlipListResponse",
    "GetPackingSlipResponse",
    "SubmitShippingLabelsRequestBody",
    "ShippingLabelRequestBody",
    "Item",
    "PackedItem",
    "PartyIdentification",
    "ShipmentDetails",
    "StatusUpdateDetails",
    "TaxRegistrationDetails",
    "Address",
    "Dimensions",
    "Weight",
    "Decimal",
    "ItemQuantity",
    "SubmitShipmentConfirmationsResponse",
    "SubmitShipmentStatusUpdatesResponse",
    "GetShippingLabelListResponse",
    "GetShippingLabelResponse",
    "ShippingLabelList",
    "LabelData",
    "ShippingLabel",
    "SubmitShippingLabelsResponse",
    "SubmitShipmentConfirmationsRequestBody",
    "ShipmentConfirmation",
    "SubmitShipmentStatusUpdatesRequestBody",
    "ShipmentStatusUpdate",
    "GetCustomerInvoicesResponse",
    "GetCustomerInvoiceResponse",
    "CustomerInvoiceList",
    "Pagination",
    "CustomerInvoice",
    "TransactionReference",
    "ErrorList",
    "Error",
    "Container",
    "GetShippingLabelsRequest",
    "SubmitShippingLabelRequestBodyRequest",
    "GetShippingLabelRequest",
    "SubmitShipmentConfirmationsRequest",
    "SubmitShipmentStatusUpdatesRequest",
    "GetCustomerInvoicesRequest",
    "GetCustomerInvoiceRequest",
    "GetPackingSlipsRequest",
    "GetPackingSlipRequest",
]
