# coding: utf-8

"""
    Selling Partner API for Product Fees

    The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.fees_estimate_error_detail import FeesEstimateErrorDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestFeesEstimateErrorDetail(unittest.TestCase):
    """FeesEstimateErrorDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeesEstimateErrorDetail(self):
        """Test FeesEstimateErrorDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fees_estimate_error_detail.FeesEstimateErrorDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
