"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (AdditionalInputs, AdditionalInputsList,
                     AdditionalSellerInput, AdditionalSellerInputs,
                     AdditionalSellerInputsList, Address, AddressLine1,
                     AddressLine2, AddressLine3, AddressName, AmazonOrderId,
                     AvailableCarrierWillPickUpOption,
                     AvailableCarrierWillPickUpOptionsList,
                     AvailableDeliveryExperienceOption,
                     AvailableDeliveryExperienceOptionsList,
                     AvailableFormatOptionsForLabel,
                     AvailableFormatOptionsForLabelList,
                     AvailableShippingServiceOptions, Benefits,
                     CancelShipmentRequest, CancelShipmentResponse,
                     CarrierWillPickUpOption, City, Constraint, Constraints,
                     CountryCode, CreateShipmentRequest,
                     CreateShipmentRequestBody, CreateShipmentResponse,
                     CurrencyAmount, CustomTextForLabel, DangerousGoodsDetails,
                     DeliveryExperienceOption, DeliveryExperienceType,
                     DistrictOrCounty, EmailAddress, Error, ErrorList,
                     ExcludedBenefit, ExcludedBenefitReasonCodes,
                     ExcludedBenefits, FileContents, FileType,
                     GetAdditionalSellerInputsRequest,
                     GetAdditionalSellerInputsRequestBody,
                     GetAdditionalSellerInputsResponse,
                     GetAdditionalSellerInputsResult,
                     GetEligibleShipmentServicesRequest,
                     GetEligibleShipmentServicesRequestBody,
                     GetEligibleShipmentServicesResponse,
                     GetEligibleShipmentServicesResult, GetShipmentRequest,
                     GetShipmentResponse, HazmatType, IncludedBenefits,
                     InputTargetType, Item, ItemDescription, ItemLevelFields,
                     ItemLevelFieldsList, ItemList, ItemQuantity, Label,
                     LabelCustomization, LabelDimension, LabelDimensions,
                     LabelFormat, LabelFormatList, LabelFormatOption,
                     LabelFormatOptionRequestBody, Length, LiquidVolume,
                     OrderItemId, PackageDimension, PackageDimensions,
                     PhoneNumber, PostalCode, PredefinedPackageDimensions,
                     RejectedShippingService, RejectedShippingServiceList,
                     RestrictedSetValues, SellerInputDefinition, SellerOrderId,
                     Shipment, ShipmentId, ShipmentRequestDetails,
                     ShipmentStatus, ShippingOfferingFilter, ShippingService,
                     ShippingServiceIdentifier, ShippingServiceList,
                     ShippingServiceOptions, StandardIdForLabel,
                     StateOrProvinceCode, TemporarilyUnavailableCarrier,
                     TemporarilyUnavailableCarrierList,
                     TermsAndConditionsNotAcceptedCarrier,
                     TermsAndConditionsNotAcceptedCarrierList, Timestamp,
                     TrackingId, TransparencyCode, TransparencyCodeList,
                     UnitOfLength, UnitOfWeight, Weight, WeightValue)

__all__ = [
    "Error",
    "ErrorList",
    "LabelFormatOptionRequestBody",
    "LabelFormatOption",
    "AvailableCarrierWillPickUpOption",
    "AvailableCarrierWillPickUpOptionsList",
    "AvailableDeliveryExperienceOption",
    "AvailableDeliveryExperienceOptionsList",
    "AvailableShippingServiceOptions",
    "AvailableFormatOptionsForLabel",
    "AvailableFormatOptionsForLabelList",
    "Constraint",
    "Constraints",
    "AdditionalInputs",
    "SellerInputDefinition",
    "InputTargetType",
    "AdditionalInputsList",
    "AdditionalSellerInput",
    "AdditionalSellerInputs",
    "AdditionalSellerInputsList",
    "Address",
    "AddressLine1",
    "AddressLine2",
    "AddressLine3",
    "AddressName",
    "AmazonOrderId",
    "Benefits",
    "IncludedBenefits",
    "ExcludedBenefits",
    "ExcludedBenefit",
    "ExcludedBenefitReasonCodes",
    "CancelShipmentResponse",
    "City",
    "CountryCode",
    "CreateShipmentRequestBody",
    "CreateShipmentResponse",
    "ItemLevelFields",
    "ItemLevelFieldsList",
    "GetAdditionalSellerInputsRequestBody",
    "GetAdditionalSellerInputsResult",
    "GetAdditionalSellerInputsResponse",
    "CurrencyAmount",
    "CustomTextForLabel",
    "DeliveryExperienceType",
    "DistrictOrCounty",
    "EmailAddress",
    "FileContents",
    "FileType",
    "GetEligibleShipmentServicesRequestBody",
    "GetEligibleShipmentServicesResponse",
    "GetEligibleShipmentServicesResult",
    "GetShipmentResponse",
    "HazmatType",
    "Item",
    "ItemList",
    "ItemQuantity",
    "ItemDescription",
    "Label",
    "LabelCustomization",
    "LabelDimension",
    "LabelDimensions",
    "LabelFormat",
    "LabelFormatList",
    "Length",
    "OrderItemId",
    "PackageDimension",
    "PackageDimensions",
    "PhoneNumber",
    "PostalCode",
    "PredefinedPackageDimensions",
    "RestrictedSetValues",
    "SellerOrderId",
    "Shipment",
    "ShipmentId",
    "ShipmentRequestDetails",
    "ShipmentStatus",
    "DeliveryExperienceOption",
    "ShippingOfferingFilter",
    "ShippingService",
    "ShippingServiceIdentifier",
    "ShippingServiceList",
    "ShippingServiceOptions",
    "CarrierWillPickUpOption",
    "StandardIdForLabel",
    "StateOrProvinceCode",
    "RejectedShippingService",
    "RejectedShippingServiceList",
    "TemporarilyUnavailableCarrier",
    "TemporarilyUnavailableCarrierList",
    "TermsAndConditionsNotAcceptedCarrier",
    "TermsAndConditionsNotAcceptedCarrierList",
    "Timestamp",
    "TrackingId",
    "TransparencyCode",
    "TransparencyCodeList",
    "UnitOfLength",
    "UnitOfWeight",
    "Weight",
    "WeightValue",
    "LiquidVolume",
    "DangerousGoodsDetails",
    "GetEligibleShipmentServicesRequest",
    "GetShipmentRequest",
    "CancelShipmentRequest",
    "CreateShipmentRequest",
    "GetAdditionalSellerInputsRequest",
]
