"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (AcceptedRate, Account, AccountId, Address,
                     CancelShipmentRequest, CancelShipmentResponse, City,
                     ClientReferenceId, Container, ContainerItem,
                     ContainerList, ContainerReferenceId,
                     ContainerSpecification, ContainerSpecificationList,
                     CountryCode, CreateShipmentRequest,
                     CreateShipmentRequestBody, CreateShipmentResponse,
                     CreateShipmentResult, Currency, Dimensions, Error,
                     ErrorList, Event, EventCode, EventList,
                     GetAccountResponse, GetRatesRequest, GetRatesRequestBody,
                     GetRatesResponse, GetRatesResult, GetShipmentRequest,
                     GetShipmentResponse, GetTrackingInformationRequest,
                     GetTrackingInformationResponse, Label, LabelResult,
                     LabelResultList, LabelSpecification, LabelStream,
                     Location, Party, PostalCode, PromisedDeliveryDate,
                     PurchaseLabelsRequest, PurchaseLabelsRequestBody,
                     PurchaseLabelsResponse, PurchaseLabelsResult,
                     PurchaseShipmentRequest, PurchaseShipmentRequestBody,
                     PurchaseShipmentResponse, PurchaseShipmentResult, Rate,
                     RateId, RateList, RetrieveShippingLabelRequest,
                     RetrieveShippingLabelRequestBody,
                     RetrieveShippingLabelResponse,
                     RetrieveShippingLabelResult, ServiceRate, ServiceRateList,
                     ServiceType, ServiceTypeList, Shipment, ShipmentId,
                     ShippingPromiseSet, StateOrRegion, TimeRange, TrackingId,
                     TrackingInformation, TrackingSummary, Weight)

__all__ = [
    "Error",
    "ErrorList",
    "AccountId",
    "ShipmentId",
    "ClientReferenceId",
    "ContainerReferenceId",
    "EventCode",
    "StateOrRegion",
    "City",
    "CountryCode",
    "PostalCode",
    "Location",
    "Event",
    "EventList",
    "TrackingId",
    "TrackingSummary",
    "PromisedDeliveryDate",
    "Address",
    "TimeRange",
    "ShippingPromiseSet",
    "ServiceType",
    "ServiceTypeList",
    "Rate",
    "RateList",
    "RateId",
    "AcceptedRate",
    "ServiceRate",
    "ServiceRateList",
    "Party",
    "Currency",
    "Dimensions",
    "Weight",
    "ContainerItem",
    "Container",
    "ContainerList",
    "ContainerSpecification",
    "ContainerSpecificationList",
    "Label",
    "LabelResult",
    "LabelResultList",
    "LabelStream",
    "LabelSpecification",
    "CreateShipmentRequestBody",
    "PurchaseLabelsRequestBody",
    "RetrieveShippingLabelRequestBody",
    "GetRatesRequestBody",
    "PurchaseShipmentRequestBody",
    "CreateShipmentResult",
    "Shipment",
    "PurchaseLabelsResult",
    "RetrieveShippingLabelResult",
    "Account",
    "GetRatesResult",
    "PurchaseShipmentResult",
    "TrackingInformation",
    "CreateShipmentResponse",
    "GetShipmentResponse",
    "GetRatesResponse",
    "PurchaseShipmentResponse",
    "CancelShipmentResponse",
    "PurchaseLabelsResponse",
    "RetrieveShippingLabelResponse",
    "GetAccountResponse",
    "GetTrackingInformationResponse",
    "CreateShipmentRequest",
    "GetShipmentRequest",
    "CancelShipmentRequest",
    "PurchaseLabelsRequest",
    "RetrieveShippingLabelRequest",
    "PurchaseShipmentRequest",
    "GetRatesRequest",
    "GetTrackingInformationRequest",
]
