# coding: utf-8

"""
    Selling Partner API for Pricing

    The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.seller_feedback_type import SellerFeedbackType  # noqa: E501
from swagger_client.rest import ApiException


class TestSellerFeedbackType(unittest.TestCase):
    """SellerFeedbackType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSellerFeedbackType(self):
        """Test SellerFeedbackType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.seller_feedback_type.SellerFeedbackType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
