# coding: utf-8

"""
    Selling Partner API for Pricing

    The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.detailed_shipping_time_type import DetailedShippingTimeType  # noqa: E501
from swagger_client.rest import ApiException


class TestDetailedShippingTimeType(unittest.TestCase):
    """DetailedShippingTimeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailedShippingTimeType(self):
        """Test DetailedShippingTimeType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.detailed_shipping_time_type.DetailedShippingTimeType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
