# coding: utf-8

"""
    Selling Partner API for Pricing

    The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.fulfillment_channel_type import FulfillmentChannelType  # noqa: E501
from swagger_client.rest import ApiException


class TestFulfillmentChannelType(unittest.TestCase):
    """FulfillmentChannelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFulfillmentChannelType(self):
        """Test FulfillmentChannelType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fulfillment_channel_type.FulfillmentChannelType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
