# coding: utf-8

"""
    Selling Partner API for Pricing

    The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.lowest_price_type import LowestPriceType  # noqa: E501
from swagger_client.rest import ApiException


class TestLowestPriceType(unittest.TestCase):
    """LowestPriceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLowestPriceType(self):
        """Test LowestPriceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lowest_price_type.LowestPriceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
