"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (URL, AmazonOrderId, Code,
                     CreateScheduledPackageBulkRequest,
                     CreateScheduledPackageRequest,
                     CreateScheduledPackageRequestBody,
                     CreateScheduledPackagesRequestBody,
                     CreateScheduledPackagesResponse, DateTime, Dimension,
                     Dimensions, Error, ErrorList, GetScheduledPackageRequest,
                     HandoverMethod, InvoiceData, Item, Items, LabelFormat,
                     ListHandoverSlotsRequest, ListHandoverSlotsRequestBody,
                     ListHandoverSlotsResponse, OrderItemId,
                     OrderItemSerialNumber, OrderItemSerialNumbers,
                     OrderScheduleDetails, Package, PackageDetails, PackageId,
                     PackageIdentifier, Packages, PackageStatus, RejectedOrder,
                     ScheduledPackageId, String, TimeSlot, TimeSlots,
                     TrackingDetails, UnitOfLength, UnitOfWeight,
                     UpdatePackageDetails, UpdatePackageDetailsList,
                     UpdateScheduledPackagesRequest,
                     UpdateScheduledPackagesRequestBody, Weight, WeightValue)

__all__ = [
    "PackageIdentifier",
    "PackageStatus",
    "PackageId",
    "TrackingDetails",
    "HandoverMethod",
    "OrderScheduleDetails",
    "AmazonOrderId",
    "Dimension",
    "Dimensions",
    "ListHandoverSlotsRequestBody",
    "ListHandoverSlotsResponse",
    "InvoiceData",
    "Item",
    "Items",
    "OrderItemId",
    "OrderItemSerialNumber",
    "OrderItemSerialNumbers",
    "Package",
    "Packages",
    "PackageDetails",
    "RejectedOrder",
    "TimeSlot",
    "TimeSlots",
    "ScheduledPackageId",
    "CreateScheduledPackageRequestBody",
    "UpdateScheduledPackagesRequestBody",
    "UpdatePackageDetails",
    "UpdatePackageDetailsList",
    "String",
    "DateTime",
    "UnitOfLength",
    "UnitOfWeight",
    "CreateScheduledPackagesRequestBody",
    "CreateScheduledPackagesResponse",
    "URL",
    "LabelFormat",
    "Weight",
    "WeightValue",
    "ErrorList",
    "Error",
    "Code",
    "ListHandoverSlotsRequest",
    "GetScheduledPackageRequest",
    "CreateScheduledPackageRequest",
    "UpdateScheduledPackagesRequest",
    "CreateScheduledPackageBulkRequest",
]
