"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Asin, ASINIdentifier, AttributeSetList,
                     BatchOffersRequestParams, BatchOffersResponse,
                     BatchRequestBody, BuyBoxEligibleOffers, BuyBoxPrices,
                     BuyBoxPriceType, CompetitivePriceList,
                     CompetitivePriceType, CompetitivePricingType,
                     ConditionType, CustomerType, DetailedShippingTimeType,
                     Error, ErrorList, Errors, FulfillmentChannelType,
                     GetCompetitivePricingRequest, GetItemOffersBatchRequest,
                     GetItemOffersBatchRequestBody, GetItemOffersBatchResponse,
                     GetItemOffersRequest, GetListingOffersBatchRequest,
                     GetListingOffersBatchRequestBody,
                     GetListingOffersBatchResponse, GetListingOffersRequest,
                     GetOffersHttpStatusLine, GetOffersResponse,
                     GetOffersResult, GetPricingRequest, GetPricingResponse,
                     HttpMethod, HttpRequestHeaders, HttpResponseHeaders,
                     IdentifierType, ItemCondition, ItemIdentifier,
                     ItemOffersRequestBody, ItemOffersRequestList,
                     ItemOffersRequestParams, ItemOffersResponse,
                     ItemOffersResponseList, ListingOffersRequestBody,
                     ListingOffersRequestList, ListingOffersRequestParams,
                     ListingOffersResponse, ListingOffersResponseList,
                     LowestPrices, LowestPriceType, MarketplaceId, MoneyType,
                     NumberOfOfferListingsList, NumberOfOffers, OfferCountType,
                     OfferCustomerType, OfferDetail, OfferDetailList,
                     OfferListingCountType, OffersList, OfferType, Points,
                     Price, PriceList, PriceType, PrimeInformationType,
                     Product, QuantityDiscountPriceType, QuantityDiscountType,
                     RelationshipList, SalesRankList, SalesRankType,
                     SellerFeedbackType, SellerSKUIdentifier, ShipsFromType,
                     Summary)

__all__ = [
    "GetItemOffersBatchRequestBody",
    "GetListingOffersBatchRequestBody",
    "ListingOffersRequestList",
    "ItemOffersRequestList",
    "BatchOffersRequestParams",
    "ItemOffersRequestBody",
    "ListingOffersRequestBody",
    "GetItemOffersBatchResponse",
    "GetListingOffersBatchResponse",
    "ItemOffersResponseList",
    "ListingOffersResponseList",
    "BatchOffersResponse",
    "ItemOffersRequestParams",
    "ItemOffersResponse",
    "ListingOffersRequestParams",
    "ListingOffersResponse",
    "Errors",
    "GetPricingResponse",
    "GetOffersResponse",
    "PriceList",
    "GetOffersResult",
    "HttpRequestHeaders",
    "HttpResponseHeaders",
    "GetOffersHttpStatusLine",
    "HttpMethod",
    "BatchRequestBody",
    "Price",
    "Product",
    "IdentifierType",
    "ASINIdentifier",
    "SellerSKUIdentifier",
    "AttributeSetList",
    "RelationshipList",
    "CompetitivePricingType",
    "CompetitivePriceList",
    "CompetitivePriceType",
    "NumberOfOfferListingsList",
    "OfferListingCountType",
    "MoneyType",
    "SalesRankList",
    "SalesRankType",
    "PriceType",
    "OffersList",
    "OfferType",
    "OfferCustomerType",
    "QuantityDiscountPriceType",
    "QuantityDiscountType",
    "Points",
    "ConditionType",
    "ItemIdentifier",
    "Summary",
    "BuyBoxEligibleOffers",
    "BuyBoxPrices",
    "LowestPrices",
    "NumberOfOffers",
    "OfferCountType",
    "FulfillmentChannelType",
    "LowestPriceType",
    "BuyBoxPriceType",
    "OfferDetailList",
    "OfferDetail",
    "PrimeInformationType",
    "SellerFeedbackType",
    "ErrorList",
    "DetailedShippingTimeType",
    "ShipsFromType",
    "MarketplaceId",
    "ItemCondition",
    "Asin",
    "CustomerType",
    "Error",
    "GetPricingRequest",
    "GetCompetitivePricingRequest",
    "GetListingOffersRequest",
    "GetItemOffersRequest",
    "GetItemOffersBatchRequest",
    "GetListingOffersBatchRequest",
]
