"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (Address, AmazonPrepFeesDetails, AmazonPrepFeesDetailsList,
                     Amount, ASINPrepInstructions, ASINPrepInstructionsList,
                     BarcodeInstruction, BigDecimalType,
                     BillOfLadingDownloadURL, BoxContentsFeeDetails,
                     BoxContentsSource, CurrencyCode, DateStringType, Error,
                     ErrorList, ErrorReason, GetBillOfLadingRequest,
                     GetBillOfLadingResponse, GetLabelsRequest,
                     GetLabelsResponse, GetPrepInstructionsRequest,
                     GetPrepInstructionsResponse, GetPrepInstructionsResult,
                     GetShipmentItemsByShipmentIdRequest,
                     GetShipmentItemsRequest, GetShipmentItemsResponse,
                     GetShipmentItemsResult, GetShipmentsRequest,
                     GetShipmentsResponse, GetShipmentsResult,
                     InboundShipmentInfo, InboundShipmentItem,
                     InboundShipmentItemList, InboundShipmentList, InvalidASIN,
                     InvalidASINList, InvalidSKU, InvalidSKUList,
                     LabelDownloadURL, LabelPrepType, PrepDetails,
                     PrepDetailsList, PrepGuidance, PrepInstruction,
                     PrepInstructionList, PrepOwner, Quantity, ShipmentStatus,
                     SKUPrepInstructions, SKUPrepInstructionsList)

__all__ = [
    "Error",
    "ErrorList",
    "ASINPrepInstructions",
    "ASINPrepInstructionsList",
    "Address",
    "AmazonPrepFeesDetails",
    "AmazonPrepFeesDetailsList",
    "Amount",
    "BarcodeInstruction",
    "BigDecimalType",
    "BoxContentsFeeDetails",
    "BoxContentsSource",
    "CurrencyCode",
    "DateStringType",
    "ErrorReason",
    "GetBillOfLadingResponse",
    "LabelDownloadURL",
    "BillOfLadingDownloadURL",
    "GetLabelsResponse",
    "GetPrepInstructionsResult",
    "GetPrepInstructionsResponse",
    "InboundShipmentInfo",
    "InboundShipmentItem",
    "InboundShipmentItemList",
    "InboundShipmentList",
    "InvalidASIN",
    "InvalidASINList",
    "InvalidSKU",
    "InvalidSKUList",
    "LabelPrepType",
    "GetShipmentItemsResult",
    "GetShipmentItemsResponse",
    "GetShipmentsResult",
    "GetShipmentsResponse",
    "PrepDetails",
    "PrepDetailsList",
    "PrepGuidance",
    "PrepInstruction",
    "PrepInstructionList",
    "PrepOwner",
    "Quantity",
    "SKUPrepInstructions",
    "SKUPrepInstructionsList",
    "ShipmentStatus",
    "GetPrepInstructionsRequest",
    "GetLabelsRequest",
    "GetBillOfLadingRequest",
    "GetShipmentsRequest",
    "GetShipmentItemsByShipmentIdRequest",
    "GetShipmentItemsRequest",
]
