# coding: utf-8

"""
    Selling Partner API for Finances

    The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.charge_instrument import ChargeInstrument  # noqa: E501
from swagger_client.rest import ApiException


class TestChargeInstrument(unittest.TestCase):
    """ChargeInstrument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChargeInstrument(self):
        """Test ChargeInstrument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.charge_instrument.ChargeInstrument()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
