# coding: utf-8

"""
    Selling Partner API for Sales

    The Selling Partner API for Sales provides APIs related to sales performance.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.order_metrics_interval import OrderMetricsInterval  # noqa: E501
from swagger_client.rest import ApiException


class TestOrderMetricsInterval(unittest.TestCase):
    """OrderMetricsInterval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderMetricsInterval(self):
        """Test OrderMetricsInterval"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.order_metrics_interval.OrderMetricsInterval()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
