"""
Generated models package from Swagger/OpenAPI specification.
This file was auto-generated. Do not edit manually.
"""

from .base_models import RequestsBaseModel
from .common import (AccessibilityAttributes, AccessPoint, AccessPointDetails,
                     AccessPointId, AccessPointList, AccessPointsMap,
                     AccessPointType, AccountId, AccountStatus, AccountType,
                     ActiveAccount, ActiveAccounts, AdditionalAddressNotes,
                     Address, AlternateLegTrackingId, AmazonOrderDetails,
                     AmazonShipmentDetails, AvailableValueAddedServiceGroup,
                     AvailableValueAddedServiceGroupList, Benefits,
                     CancelShipmentRequest, CancelShipmentResponse,
                     CancelShipmentResult, Carrier, CarrierAccount,
                     CarrierAccountAttribute, CarrierAccountAttributes,
                     CarrierAccountInput, CarrierAccountInputsList,
                     CarrierAccounts, CarrierAccountType, CarrierId,
                     CarrierName, ChannelDetails, ChannelType, ChargeComponent,
                     ChargeList, City, ClaimId, ClaimProofURLs, ClaimReason,
                     ClientReferenceDetail, ClientReferenceDetails,
                     CollectionFormId, CollectionFormsHistoryRecord,
                     CollectionFormsHistoryRecordList, CollectionsFormDocument,
                     CollectOnDelivery, Contents, CountryCode,
                     CreateClaimRequest, CreateClaimRequestBody,
                     CreateClaimResponse, Currency, DangerousGoodsDetails,
                     DateRange, DayOfWeekTimeMap, DetailCodes, Dimensions,
                     DirectFulfillmentItemIdentifiers,
                     DirectPurchaseRequestBody, DirectPurchaseResponse,
                     DirectPurchaseResult, DirectPurchaseShipmentRequest,
                     DocumentFormat, DocumentSize, DocumentType, Dpi, Error,
                     ErrorList, Event, EventCode, ExceptionOperatingHours,
                     ExcludedBenefit, ExcludedBenefitReasonCodes,
                     ExcludedBenefits, GenerateCollectionFormRequest,
                     GenerateCollectionFormRequestBody,
                     GenerateCollectionFormResponse, GenerationStatus, Geocode,
                     GetAccessPointsRequest, GetAccessPointsResponse,
                     GetAccessPointsResult, GetAdditionalInputsRequest,
                     GetAdditionalInputsResponse, GetAdditionalInputsResult,
                     GetCarrierAccountFormInputsResponse,
                     GetCarrierAccountsRequest, GetCarrierAccountsRequestBody,
                     GetCarrierAccountsResponse,
                     GetCollectionFormHistoryRequest,
                     GetCollectionFormHistoryRequestBody,
                     GetCollectionFormHistoryResponse,
                     GetCollectionFormRequest, GetCollectionFormResponse,
                     GetRatesRequest, GetRatesRequestBody, GetRatesResponse,
                     GetRatesResult, GetShipmentDocumentsRequest,
                     GetShipmentDocumentsResponse, GetShipmentDocumentsResult,
                     GetTrackingRequest, GetTrackingResponse,
                     GetTrackingResult, GetUnmanifestedShipmentsRequest,
                     GetUnmanifestedShipmentsRequestBody,
                     GetUnmanifestedShipmentsResponse, GoodsOwner,
                     IncludedBenefits, IneligibilityReason,
                     IneligibilityReasonCode, IneligibleRate,
                     IneligibleRateList, InputType, InvoiceDetails, Item,
                     ItemList, LabelAttribute, LinkableAccountType,
                     LinkableAccountTypeList, LinkableCarrier,
                     LinkableCarriersList, LinkCarrierAccountRequest,
                     LinkCarrierAccountRequestBody, LinkCarrierAccountResponse,
                     LiquidVolume, Location, MerchantId, NdrAction,
                     NdrRequestData, NeedFileJoining, OneClickShipmentRequest,
                     OneClickShipmentRequestBody, OneClickShipmentResponse,
                     OneClickShipmentResult, OneClickShipmentValueAddedService,
                     OneClickShipmentValueAddedServiceDetails, OperatingHours,
                     Package, PackageClientReferenceId, PackageDocument,
                     PackageDocumentDetail, PackageDocumentDetailList,
                     PackageDocumentList, PackageList, PageLayout, PaymentType,
                     PostalCode, PrintOption, PrintOptionList, Promise,
                     PurchaseShipmentRequest, PurchaseShipmentRequestBody,
                     PurchaseShipmentResponse, PurchaseShipmentResult, Rate,
                     RateId, RateItem, RateItemID, RateItemList, RateItemType,
                     RateList, RequestAttributes,
                     RequestedDocumentSpecification,
                     RequestedLabelCustomization, RequestedValueAddedService,
                     RequestedValueAddedServiceList, RequestToken, Service,
                     ServiceId, ServiceIds, ServiceName, ServiceSelection,
                     SettlementType, ShipmentId, ShipmentType,
                     ShipperInstruction, StateOrRegion, Status,
                     SubmitNdrFeedbackRequest, SubmitNdrFeedbackRequestBody,
                     SupportedDocumentDetail, SupportedDocumentSpecification,
                     SupportedDocumentSpecificationList, TaxDetail,
                     TaxDetailList, TaxType, TimeOfDay, TimeWindow,
                     TrackingDetailCodes, TrackingId, TrackingSummary,
                     UnlinkCarrierAccountRequest,
                     UnlinkCarrierAccountRequestBody,
                     UnlinkCarrierAccountResponse,
                     UnmanifestedCarrierInformation,
                     UnmanifestedCarrierInformationList,
                     UnmanifestedShipmentLocation,
                     UnmanifestedShipmentLocationList, ValidationMetadata,
                     ValidationMetadataList, ValueAddedService,
                     ValueAddedServiceDetails, Weight)

__all__ = [
    "Error",
    "ErrorList",
    "Weight",
    "LiquidVolume",
    "InvoiceDetails",
    "ChargeList",
    "ChargeComponent",
    "Currency",
    "Dimensions",
    "RequestToken",
    "RateId",
    "CarrierId",
    "AccountId",
    "CarrierName",
    "PackageClientReferenceId",
    "ShipmentId",
    "DetailCodes",
    "TrackingDetailCodes",
    "TrackingId",
    "ClaimId",
    "AlternateLegTrackingId",
    "ServiceId",
    "ServiceName",
    "AdditionalAddressNotes",
    "ShipperInstruction",
    "Address",
    "Geocode",
    "StateOrRegion",
    "City",
    "CountryCode",
    "PostalCode",
    "Location",
    "DocumentFormat",
    "DocumentType",
    "Dpi",
    "PageLayout",
    "NeedFileJoining",
    "Contents",
    "RequestedLabelCustomization",
    "RequestAttributes",
    "LabelAttribute",
    "PackageDocumentList",
    "PackageDocument",
    "PrintOptionList",
    "PrintOption",
    "DocumentSize",
    "SupportedDocumentDetail",
    "RequestedDocumentSpecification",
    "SupportedDocumentSpecificationList",
    "SupportedDocumentSpecification",
    "Item",
    "ItemList",
    "Package",
    "PackageList",
    "DirectFulfillmentItemIdentifiers",
    "PackageDocumentDetail",
    "PackageDocumentDetailList",
    "TimeWindow",
    "Promise",
    "RequestedValueAddedServiceList",
    "RequestedValueAddedService",
    "AvailableValueAddedServiceGroupList",
    "AvailableValueAddedServiceGroup",
    "ValueAddedService",
    "CollectOnDelivery",
    "ValueAddedServiceDetails",
    "DangerousGoodsDetails",
    "TaxType",
    "TaxDetail",
    "TaxDetailList",
    "GoodsOwner",
    "EventCode",
    "Event",
    "TrackingSummary",
    "Status",
    "AmazonOrderDetails",
    "AmazonShipmentDetails",
    "ChannelType",
    "ChannelDetails",
    "RateList",
    "Rate",
    "IneligibilityReasonCode",
    "IneligibilityReason",
    "IneligibleRate",
    "IneligibleRateList",
    "CancelShipmentResult",
    "CancelShipmentResponse",
    "GetRatesRequestBody",
    "AccessPointDetails",
    "NdrAction",
    "NdrRequestData",
    "ClaimReason",
    "ClaimProofURLs",
    "SettlementType",
    "GetRatesResult",
    "GetRatesResponse",
    "DirectPurchaseRequestBody",
    "DirectPurchaseResult",
    "DirectPurchaseResponse",
    "GetShipmentDocumentsResult",
    "GetShipmentDocumentsResponse",
    "GetTrackingResult",
    "SubmitNdrFeedbackRequestBody",
    "CreateClaimRequestBody",
    "GetTrackingResponse",
    "CreateClaimResponse",
    "PurchaseShipmentRequestBody",
    "PurchaseShipmentResult",
    "PurchaseShipmentResponse",
    "OneClickShipmentRequestBody",
    "OneClickShipmentResponse",
    "OneClickShipmentResult",
    "GetAccessPointsResponse",
    "GetAccessPointsResult",
    "AccessPointType",
    "AccessPointsMap",
    "AccessPointList",
    "AccessPointId",
    "AccessPoint",
    "AccessibilityAttributes",
    "OperatingHours",
    "TimeOfDay",
    "DayOfWeekTimeMap",
    "ExceptionOperatingHours",
    "GetAdditionalInputsResult",
    "GetAdditionalInputsResponse",
    "GetCarrierAccountsRequestBody",
    "LinkCarrierAccountRequestBody",
    "UnlinkCarrierAccountRequestBody",
    "GenerateCollectionFormRequestBody",
    "GetCollectionFormHistoryRequestBody",
    "GetUnmanifestedShipmentsRequestBody",
    "GetCarrierAccountFormInputsResponse",
    "GetCarrierAccountsResponse",
    "LinkCarrierAccountResponse",
    "UnlinkCarrierAccountResponse",
    "GenerateCollectionFormResponse",
    "GetCollectionFormHistoryResponse",
    "GetUnmanifestedShipmentsResponse",
    "GetCollectionFormResponse",
    "ClientReferenceDetails",
    "ClientReferenceDetail",
    "CollectionFormId",
    "ShipmentType",
    "CarrierAccounts",
    "CarrierAccount",
    "ActiveAccounts",
    "ActiveAccount",
    "DateRange",
    "CarrierAccountAttributes",
    "CarrierAccountAttribute",
    "CarrierAccountType",
    "MerchantId",
    "AccountStatus",
    "CollectionsFormDocument",
    "CollectionFormsHistoryRecordList",
    "CollectionFormsHistoryRecord",
    "UnmanifestedCarrierInformationList",
    "UnmanifestedCarrierInformation",
    "UnmanifestedShipmentLocationList",
    "UnmanifestedShipmentLocation",
    "LinkableCarriersList",
    "LinkableCarrier",
    "LinkableAccountTypeList",
    "LinkableAccountType",
    "CarrierAccountInputsList",
    "CarrierAccountInput",
    "ValidationMetadataList",
    "ValidationMetadata",
    "GenerationStatus",
    "AccountType",
    "InputType",
    "PaymentType",
    "RateItemList",
    "RateItem",
    "RateItemID",
    "RateItemType",
    "Benefits",
    "IncludedBenefits",
    "ExcludedBenefits",
    "ExcludedBenefit",
    "ExcludedBenefitReasonCodes",
    "ServiceSelection",
    "ServiceIds",
    "OneClickShipmentValueAddedServiceDetails",
    "OneClickShipmentValueAddedService",
    "Service",
    "Carrier",
    "GetRatesRequest",
    "DirectPurchaseShipmentRequest",
    "PurchaseShipmentRequest",
    "OneClickShipmentRequest",
    "GetTrackingRequest",
    "GetShipmentDocumentsRequest",
    "CancelShipmentRequest",
    "GetAdditionalInputsRequest",
    "GetCarrierAccountsRequest",
    "LinkCarrierAccountRequest",
    "UnlinkCarrierAccountRequest",
    "GenerateCollectionFormRequest",
    "GetCollectionFormHistoryRequest",
    "GetUnmanifestedShipmentsRequest",
    "GetCollectionFormRequest",
    "GetAccessPointsRequest",
    "SubmitNdrFeedbackRequest",
    "CreateClaimRequest",
]
